### ISSUE TITLE
Incompatibile types when assigning to type 'nuitka_bool'

### ISSUE THREAD

**Issue by poke2201** [Nuitka/Nuitka#439]
Nuitka version: 0.6.4 stable
Python version 3.7
Windows 10

Installed using .msi package

My program was able to compile in 0.6.3, but I added extra code that mainly deals with internal program logic and refactoring.  I tried the Hello World test file and got it to work, so its not a set up issue.

The program gets a specific error after all the warnings nuitka spits out:
```
FinalGUI.build\module.Program.c: In function 'impl_Program$$$function_1_SearchFiles':
FinalGUI.build\module.Program.c:1332:34: error: incompatible types when assigning to type nuitka_bool' {aka 'enum <anonymous>'} from type 'PyObject *' {aka 'struct _object *'}
             tmp_or_right_value_1 = Py_None;
                                  ^
scons: *** [FinalGUI.build\module.Program.o] Error 1
```
My code I push through an admin level cmd is:
```
C:\ V1.1>python -m nuitka --standalone --mingw64 --experimental=use_pefile --plugin-enable=qt-plugins FinalGUI.py
```

I've added a screenshot of my cmd as well.
<img width="490" alt="nuitka_error" src="https://user-images.githubusercontent.com/48573359/59951973-83f8b880-942f-11e9-9ce9-c68b4a0b6ad7.PNG">

**Comment by kayhayen** [comment]
You didn't try develop, did you? I think this might be an issue recently fixed.

Yours,
Kay

**Comment by poke2201** [comment]
Yeah it worked on develop.  For the sake of knowledge, can you explain what happened to the program there?  I'm rather novice at programming so I want to learn more.

**Comment by kayhayen** [comment]
Hello there,

so Nuitka currently optimizes some code to use C boolean types, e.g. when
used in conditions. In many cases the value "None" in a
bool context is replace with static truth (or rather falseness) of the
condition value.

However, for code like this:

```
if x or None:
    something()
```

Nuitka currently cannot do it, because the boolean test on `x or None`
might be required. But turns out, the code generation didn't
handle that case of having to produce a C boolean value for `None`.

So most probably, your code changes introduced a mistake. If you look at
the function name in C, you might get an idea, if you
look for these things. Typically this kind of code is a programming
mistake. It was in the case of the first reporter of the bug
anyway.

Yours,
Kay

**Comment by poke2201** [comment]
Oh okay, I'll take a look.  Thanks for the info!
