### ISSUE TITLE
PendulumUsing failing on Python 2: AttributeError: 'tuple' object has no attribute 'name'

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#1246]
I am encountering this on Nuitka 0.6.17.3 builds on openSUSE Leap 15.3.  I havent done Nuitka builds since 0.6.14.7, and likely never done PendulumUsing due to https://github.com/Nuitka/Nuitka/issues/1037, so this problem may date back to when `PendulumUsing.py` was added.

The version of pendulum is `python2-pendulum-2.0.5-bp153.1.14`, where `bp153` probably means base-package for Leap 15.3

I can not easily update to pendulum 2.1.x as the builds now depend on poetry, which isnt available for py2.

The test is run with gcc (as PendulumUsing OOMs on clang) and with `NUITKA_EXTRA_OPTIONS="--debug"`

```
[ 6133s] Consider output of standalone mode compiled program: PendulumUsing.py
[ 6133s] Comparing output of 'PendulumUsing.py' using '/usr/bin/python2' with flags silent, expect_success, --standalone, remove_output, cpython_cache, timing ...
[ 6145s] --- /usr/bin/python2 (stdout)
[ 6145s] +++ nuitka (stdout)
[ 6145s] 
[ 6145s] @@ -1,2 +1 @@
[ 6145s] 
[ 6145s] -OK
[ 6145s]  
[ 6145s] --- /usr/bin/python2 (stderr)
[ 6145s] +++ nuitka (stderr)
[ 6145s] 
[ 6145s] @@ -1 +1,31 @@
[ 6145s] 
[ 6145s] +Traceback (most recent call last):
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/__main__.py", line 187, in <module>
[ 6145s] +    main()
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/__main__.py", line 173, in main
[ 6145s] +    MainControl.main()
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/MainControl.py", line 744, in main
[ 6145s] +    main_module = _createNodeTree(filename=filename)
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/MainControl.py", line 173, in _createNodeTree
[ 6145s] +    Optimization.optimize(main_module.getOutputFilename())
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/optimizations/Optimization.py", line 349, in optimize
[ 6145s] +    finished = makeOptimizationPass()
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/optimizations/Optimization.py", line 312, in makeOptimizationPass
[ 6145s] +    changed = optimizeModule(current_module)
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/optimizations/Optimization.py", line 207, in optimizeModule
[ 6145s] +    changed = optimizeCompiledPythonModule(module)
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/optimizations/Optimization.py", line 156, in optimizeCompiledPythonModule
[ 6145s] +    Plugins.considerImplicitImports(module=module, signal_change=signalChange)
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/plugins/Plugins.py", line 308, in considerImplicitImports
[ 6145s] +    cls._considerImplicitImports(plugin=plugin, module=module)
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/plugins/Plugins.py", line 225, in _considerImplicitImports
[ 6145s] +    for full_name in plugin.getImplicitImports(module):
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/plugins/standard/ImplicitImports.py", line 1114, in getImplicitImports
[ 6145s] +    for item in self.getImportsByFullname(full_name, module_filename):
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/plugins/standard/ImplicitImports.py", line 1065, in getImportsByFullname
[ 6145s] +    checkImportsRecursive(full_name, module_filename)
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/plugins/standard/ImplicitImports.py", line 1058, in checkImportsRecursive
[ 6145s] +    for item in self._getImportsByFullname(module_name, module_filename):
[ 6145s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.17.3/nuitka/plugins/standard/ImplicitImports.py", line 898, in _getImportsByFullname
[ 6145s] +    yield full_name.getChildNamed(idiom.name).getChildNamed("locale")
[ 6145s] +AttributeError: 'tuple' object has no attribute 'name'
```

Also confirmed this occurs with clang.
