### ISSUE TITLE
Torch - NotFoundError.

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#1085]
**nuitka --version**
```
0.6.15rc5
Python: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
Executable: E:\YoloV5\Scripts\python.exe
OS: Windows
Arch: x86_64
```
_At the moment, the version does not matter, the same error is observed in previous versions._

command: `python -m nuitka --mingw64 --standalone --windows-uac-admin --plugin-enable=torch --plugin-enable=multiprocessing --plugin-enable=numpy --output-dir=E:\TEST\TEST\TEST "E:\TEST\detect.py"`

**code:**
```
from yolov5 import YOLOv5

# set model params
model_path = "yolov5/weights/yolov5s.pt" # it automatically downloads yolov5s model to given path
device = "cuda" # or "cpu"

# init yolov5 model
yolov5 = YOLOv5(model_path, device)

# load images
image1 = 'https://github.com/ultralytics/yolov5/raw/master/data/images/zidane.jpg'
image2 = 'https://github.com/ultralytics/yolov5/blob/master/data/images/bus.jpg'

# perform inference
results = yolov5.predict(image1)
results.show()
```

Output:
```
Traceback (most recent call last):
  File "E:\TEST\TEST\TEST\detect.dist\detect.py", line 1, in <module>
  File "E:\TEST\TEST\TEST\detect.dist\yolov5\__init__.py", line 1, in <module yolov5>
  File "E:\TEST\TEST\TEST\detect.dist\yolov5\detect.py", line 10, in <module yolov5.detect>
  File "E:\TEST\TEST\TEST\detect.dist\yolov5\models\experimental.py", line 9, in <module yolov5.models.experimental>
  File "E:\TEST\TEST\TEST\detect.dist\yolov5\models\common.py", line 12, in <module yolov5.models.common>
  File "E:\TEST\TEST\TEST\detect.dist\yolov5\utils\datasets.py", line 22, in <module yolov5.utils.datasets>
  File "E:\TEST\TEST\TEST\detect.dist\yolov5\utils\general.py", line 17, in <module yolov5.utils.general>
  File "E:\TEST\TEST\TEST\detect.dist\torchvision\__init__.py", line 6, in <module torchvision>
  File "E:\TEST\TEST\TEST\detect.dist\torchvision\models\__init__.py", line 12, in <module torchvision.models>
  File "E:\TEST\TEST\TEST\detect.dist\torchvision\models\detection\__init__.py", line 1, in <module torchvision.models.detection>
  File "E:\TEST\TEST\TEST\detect.dist\torchvision\models\detection\faster_rcnn.py", line 5, in <module torchvision.models.detection.faster_rcnn>
  File "E:\TEST\TEST\TEST\detect.dist\torchvision\ops\__init__.py", line 14, in <module torchvision.ops>
  File "E:\TEST\TEST\TEST\detect.dist\torchvision\ops\_register_onnx_ops.py", line 42, in _register_custom_op
  File "E:\TEST\TEST\TEST\detect.dist\torch\onnx\__init__.py", line 330, in register_custom_op_symbolic
  File "E:\TEST\TEST\TEST\detect.dist\torch\onnx\utils.py", line 1163, in register_custom_op_symbolic
  File "E:\TEST\TEST\TEST\detect.dist\torch\onnx\symbolic_registry.py", line 17, in <module torch.onnx.symbolic_registry>
  File "importlib.py", line 127, in import_module
ModuleNotFoundError: No module named 'torch.onnx.symbolic_opset7'
```

**Comment by kayhayen** [comment]
Is this latest torch version?

**Comment by Pro100rus32** [comment]
> Is this latest torch version?

yes, with cuda.

**Comment by Pro100rus32** [comment]
Hi @kayhayen , does this problem need funding? I can start collecting money so that I can pay you.

**Comment by kayhayen** [comment]
I managed to reproduce this, but I was busy with other things, but I fully intend to address it at some point.

**Comment by artemasd** [comment]
I have the same problem!

**Comment by Pro100rus32** [comment]
How's the progress?)

**Comment by igor-susic** [comment]
@kayhayen I would love to tackle this one, with your help of course. I'm not sure how fast will I go with my progress as I don't know the code base, but I would like to work on it if you agree.

**Comment by kayhayen** [comment]
None at all, if a tag "delayed" is seen, that's what it is. Please don't ask about progress in these cases.

**Comment by bulingda** [comment]
> **nuitka --version**
> 
> ```
> 0.6.15rc5
> Python: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
> Executable: E:\YoloV5\Scripts\python.exe
> OS: Windows
> Arch: x86_64
> ```
> 
> _At the moment, the version does not matter, the same error is observed in previous versions._
> 
> command: `python -m nuitka --mingw64 --standalone --windows-uac-admin --plugin-enable=torch --plugin-enable=multiprocessing --plugin-enable=numpy --output-dir=E:\TEST\TEST\TEST "E:\TEST\detect.py"`
> 
> **code:**
> 
> ```
> from yolov5 import YOLOv5
> 
> # set model params
> model_path = "yolov5/weights/yolov5s.pt" # it automatically downloads yolov5s model to given path
> device = "cuda" # or "cpu"
> 
> # init yolov5 model
> yolov5 = YOLOv5(model_path, device)
> 
> # load images
> image1 = 'https://github.com/ultralytics/yolov5/raw/master/data/images/zidane.jpg'
> image2 = 'https://github.com/ultralytics/yolov5/blob/master/data/images/bus.jpg'
> 
> # perform inference
> results = yolov5.predict(image1)
> results.show()
> ```
> 
> Output:
> 
> ```
> Traceback (most recent call last):
>   File "E:\TEST\TEST\TEST\detect.dist\detect.py", line 1, in <module>
>   File "E:\TEST\TEST\TEST\detect.dist\yolov5\__init__.py", line 1, in <module yolov5>
>   File "E:\TEST\TEST\TEST\detect.dist\yolov5\detect.py", line 10, in <module yolov5.detect>
>   File "E:\TEST\TEST\TEST\detect.dist\yolov5\models\experimental.py", line 9, in <module yolov5.models.experimental>
>   File "E:\TEST\TEST\TEST\detect.dist\yolov5\models\common.py", line 12, in <module yolov5.models.common>
>   File "E:\TEST\TEST\TEST\detect.dist\yolov5\utils\datasets.py", line 22, in <module yolov5.utils.datasets>
>   File "E:\TEST\TEST\TEST\detect.dist\yolov5\utils\general.py", line 17, in <module yolov5.utils.general>
>   File "E:\TEST\TEST\TEST\detect.dist\torchvision\__init__.py", line 6, in <module torchvision>
>   File "E:\TEST\TEST\TEST\detect.dist\torchvision\models\__init__.py", line 12, in <module torchvision.models>
>   File "E:\TEST\TEST\TEST\detect.dist\torchvision\models\detection\__init__.py", line 1, in <module torchvision.models.detection>
>   File "E:\TEST\TEST\TEST\detect.dist\torchvision\models\detection\faster_rcnn.py", line 5, in <module torchvision.models.detection.faster_rcnn>
>   File "E:\TEST\TEST\TEST\detect.dist\torchvision\ops\__init__.py", line 14, in <module torchvision.ops>
>   File "E:\TEST\TEST\TEST\detect.dist\torchvision\ops\_register_onnx_ops.py", line 42, in _register_custom_op
>   File "E:\TEST\TEST\TEST\detect.dist\torch\onnx\__init__.py", line 330, in register_custom_op_symbolic
>   File "E:\TEST\TEST\TEST\detect.dist\torch\onnx\utils.py", line 1163, in register_custom_op_symbolic
>   File "E:\TEST\TEST\TEST\detect.dist\torch\onnx\symbolic_registry.py", line 17, in <module torch.onnx.symbolic_registry>
>   File "importlib.py", line 127, in import_module
> ModuleNotFoundError: No module named 'torch.onnx.symbolic_opset7'
> ```

You can fix this problem by upgrading PyTorch to the highest version 1.10.

**Comment by Pro100rus32** [comment]
> You can fix this problem by upgrading PyTorch to the highest version 1.10.
@bulingda 

It doesn't work.

**test.exe**
```
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function upsample at 0x00000000603D1220>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function upsample at 0x00000000603D1310>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function interpolate at 0x00000000603D14F0>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function interpolate at 0x00000000603D15E0>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function interpolate at 0x00000000603D16D0>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function interpolate at 0x00000000603D17C0>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function upsample_nearest at 0x00000000603D19A0>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function upsample_nearest at 0x00000000603D1A90>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function upsample_bilinear at 0x00000000603D1C70>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function upsample_bilinear at 0x00000000603D1D60>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function upsample_bilinear at 0x00000000603D1E50>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function upsample_bilinear at 0x00000000603DA040>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function LSTM.forward at 0x00000000606BEC70>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function LSTM.forward at 0x00000000606BED60>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function GRU.forward at 0x00000000606C1130>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function GRU.forward at 0x00000000606C1220>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function tensordot at 0x0000000060713310>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function tensordot at 0x0000000060713400>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function tensordot at 0x00000000607134F0>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function tensordot at 0x00000000607135E0>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function norm at 0x0000000060713D60>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function norm at 0x0000000060713E50>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function norm at 0x0000000060719040>.
D:\TEST\Build\TEST\test.dist\torch\_jit_internal.py:750: UserWarning: Unable to retrieve source for @torch.jit._overload function: <compiled_function norm at 0x0000000060719130>.
Traceback (most recent call last):
  File "D:\TEST\Build\TEST\test.dist\test.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "D:\TEST\Build\TEST\test.dist\torch\__init__.py", line 721, in <module torch>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "D:\TEST\Build\TEST\test.dist\torch\utils\data\__init__.py", line 11, in <module torch.utils.data>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "D:\TEST\Build\TEST\test.dist\torch\utils\data\dataset.py", line 242, in <module torch.utils.data.dataset>
  File "D:\TEST\Build\TEST\test.dist\torch\utils\data\_typing.py", line 273, in __new__
  File "abc.py", line 85, in __new__
TypeError: _dp_init_subclass() missing 1 required positional argument: 'sub_cls'
```

**Comment by Pro100rus32** [comment]
I am going to switch to pyinstaller. Because it is unlikely that the problem will be solved(

I'm not the only one who has been waiting over six months for a solution to this problem.

**Comment by kayhayen** [comment]
Latest Torch is supposed to work with the plugin activated on 0.8.1
