### ISSUE TITLE
Windows SDK cannot be detected without "--msvc=latest"

### ISSUE THREAD

**Issue by 767251930** [Nuitka/Nuitka#3770]
# Bug Report

## 🐛 Bug Description
I have installed Visual Studio2026 and related MSVC build tools and windows sdk via Visual Studio Installer.
Nuitka cannot detect my Windows SDK unless I specify "--msvc=latest" when compiling

<img width="438" height="725" alt="Image" src="https://github.com/user-attachments/assets/b1384cac-7a63-49fd-8647-175a8d2b97ad" />

### 1. Nuitka Version, Python Version, OS, and Platform

```sh
python -m nuitka --version
4.0
Commercial: None
Python: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\ProgramFiles\Python\Python312\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Nuitka-Scons:WARNING: Windows SDK must be installed in Visual Studio for it to be usable with Nuitka. Use the Visual Studio installer for adding it.
Version C compiler: gcc (gcc 14.2.0).
```

### 2. How Nuitka and Python were Installed
```sh
python -m pip install -U Nuitka
```

## 🛠️ To Reproduce

The "main.py" is a simple "Hello World" test.
```
print("Hello World!")
```

```sh
nuitka --standalone --onefile-no-compression --enable-plugins="upx" --main="main.py" --show-scons  --msvc=latest
Nuitka-Options: Used command line options:
Nuitka-Options:   --standalone --onefile-no-compression --enable-plugins=upx --main=main.py --msvc=latest --show-scons
Nuitka: Starting Python compilation with:
Nuitka:   Version '4.0' on Python 3.12 (flavor 'CPython Official') commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Scons command: D:\ProgramFiles\Python\Python312\python.exe -W ignore
Nuitka-Scons: D:\PROGRA~1\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\INLINE~1\bin\scons.py -f
Nuitka-Scons: D:\PROGRA~1\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\BACKEN~1.SCO --jobs 16 --warn=no-deprecated
Nuitka-Scons: --no-site-dir --debug=stacktrace nuitka_src=D:\PROGRA~1\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build
Nuitka-Scons: python_version=3.12 python_prefix=D:\ProgramFiles\Python\Python312 experimental= debug_modes=
Nuitka-Scons: deployment=false no_deployment= gil_mode=true show_scons=true msvc_version=latest console_mode=force
Nuitka-Scons: noelf_mode=true target_arch=x86_64 module_mode=false dll_mode=false exe_mode=true standalone_mode=true
Nuitka-Scons: source_dir=. monolithpy=false debug_mode=false debugger_mode=false python_debug=false full_compat=false
Nuitka-Scons: trace_mode=false file_reference_mode=runtime compiled_module_count=1
Nuitka-Scons: result_exe=E:\Users\HXP\Desktop\MAIN~1.DIS\main.exe frozen_modules=153 python_sysflag_no_site=true
scons: Reading SConscript files ...
Nuitka-Scons: MSVC Environment Cache Hit (version 14.5)
Nuitka-Scons: Initial CC: 'cl'
Nuitka-Scons: Initial CCVERSION: None
Nuitka-Scons: Checking usability of binary 'D:\ProgramFiles\Microsoft Visual
Nuitka-Scons: Studio\18\Community\VC\Tools\MSVC\14.50.35717\bin\HostX64\x64\cl.exe' from environment 'cl'.
Nuitka-Scons: Using Windows SDK '10.0.26100.0'.
Nuitka-Scons: MSVC version resolved to 14.5.
Nuitka-Scons: Told to run compilation on 16 CPUs.
Nuitka-Scons: Scons: Compiler used 'D:\ProgramFiles\Microsoft Visual
Nuitka-Scons: Studio\18\Community\VC\Tools\MSVC\14.50.35717\bin\HostX64\x64\cl.exe' (MSVC 14.5).
Nuitka-Scons: Backend C compiler: cl (cl 14.5).
```

```sh
nuitka --standalone --onefile-no-compression --enable-plugins="upx" --main="main.py" --show-scons
Nuitka-Options: Used command line options:
Nuitka-Options:   --standalone --onefile-no-compression --enable-plugins=upx --main=main.py --show-scons
Nuitka: Starting Python compilation with:
Nuitka:   Version '4.0' on Python 3.12 (flavor 'CPython Official') commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Scons command: D:\ProgramFiles\Python\Python312\python.exe -W ignore
Nuitka-Scons: D:\PROGRA~1\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\INLINE~1\bin\scons.py -f
Nuitka-Scons: D:\PROGRA~1\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build\BACKEN~1.SCO --jobs 16 --warn=no-deprecated
Nuitka-Scons: --no-site-dir --debug=stacktrace nuitka_src=D:\PROGRA~1\Python\PYTHON~1\Lib\SITE-P~1\nuitka\build
Nuitka-Scons: python_version=3.12 python_prefix=D:\ProgramFiles\Python\Python312 experimental= debug_modes=
Nuitka-Scons: deployment=false no_deployment= gil_mode=true show_scons=true console_mode=force noelf_mode=true
Nuitka-Scons: target_arch=x86_64 module_mode=false dll_mode=false exe_mode=true standalone_mode=true source_dir=.
Nuitka-Scons: monolithpy=false debug_mode=false debugger_mode=false python_debug=false full_compat=false
Nuitka-Scons: trace_mode=false file_reference_mode=runtime compiled_module_count=1
Nuitka-Scons: result_exe=E:\Users\HXP\Desktop\MAIN~1.DIS\main.exe frozen_modules=153 python_sysflag_no_site=true
scons: Reading SConscript files ...
Nuitka-Scons: Initial CC: 'cl'
Nuitka-Scons: Initial CCVERSION: None
Nuitka-Scons: Checking usability of binary 'D:\ProgramFiles\Microsoft Visual
Nuitka-Scons: Studio\18\Community\VC\Tools\MSVC\14.50.35717\bin\Hostx64\x64\cl.exe' from environment 'cl'.
Nuitka-Scons:WARNING: Windows SDK must be installed in Visual Studio for it to be usable with Nuitka. Use the Visual
Nuitka-Scons:WARNING: Studio installer for adding it.
Nuitka-Scons: No usable C compiler, attempt fallback to winlibs gcc.
Nuitka-Scons: CC
Nuitka-Scons: 'C:\Users\HXP\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\14.2.0posix-19.1.1-12.0.0-msvcrt-r2\mingw64\bin\gcc.exe'
Nuitka-Scons: version check gives (14, 2, 0)
Nuitka-Scons: Told to run compilation on 16 CPUs.
Nuitka-Scons: Scons: Compiler used
Nuitka-Scons: 'C:\Users\HXP\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\14.2.0posix-19.1.1-12.0.0-msvcrt-r2\mingw64\bin\gcc.exe'.
Nuitka-Scons: Backend C compiler: gcc (gcc 14.2.0).
......
......
Nuitka-Plugins:upx: Compressing 'main.dist\main.exe'.
Nuitka: Successfully created 'E:\Users\HXP\Desktop\main.dist\main.exe'.
```

**Comment by kayhayen** [comment]
This one is very confusing to me, maybe a complexity when the MSVC environment cache was added. Noticeably you don't get a hit message. Needless to say it doesn't happen for me, because I never use MSVC prompts. Without it, both commands will work, since Nuitka + Scons will then just find what's there. This is the recommended way with Nuitka for ages. The reason simply being that users have a hard time to pick the right prompt matching their Python (and it's a nuisance extra step to run inside a special environment).

It might ignore the environment if you specifiy a version on the command line, which of course would be also not necessarily be warranted, but lead to a more healthy finding. The question becomes then, why your MSVC prompt doesn't satisfy the WinSDK version check.

Both those things are sort of bugs, lets see if I can reproduce it.

**Comment by kayhayen** [comment]
I got this in my environment when I use the "x86 native command tools prompt" and it just works.

I also got the environment as expected, what do you have?

```
WindowsSdkBinPath=C:\Program Files (x86)\Windows Kits\10\bin\
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
WindowsSDKLibVersion=10.0.26100.0\
WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\
WindowsSDKVersion=10.0.26100.0\
WindowsSDK_ExecutablePath_x64=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\
WindowsSDK_ExecutablePath_x86=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\
```

I must say that finding these prompts has become harder again, and e.g. the "Developer Command Prompt for VS" uses x86, and the others I had to actively search for.

I suspect you are encountering issues of MSVC 14.5 on non-latin systems, I got another report claiming this, that's a Russian user, but I don't think I can make it work, unless you reveal more information.

**Comment by kayhayen** [comment]
While working on this, I noticed that in case of unusable MSVC, the fallback to MinGW64 is attempted even with 3.13+ where it's going to be rejected as not suitable. It now tries zig.exe, and also while trying to give an error that it found nothing usable, it would crash in the communication between Nuitka and the --version scons part.

These are not any of your issue though.

**Comment by kayhayen** [comment]
So, I would need your input regarding the environment of your batch file, otherwise I will have to let go of this issue.

**Comment by 767251930** [comment]
> So, I would need your input regarding the environment of your batch file, otherwise I will have to let go of this issue.

how can I provide it

**Comment by kayhayen** [comment]
Fetch it from `set` command output.

**Comment by Ablinne** [comment]
I also have some problems using MSVC that started only recently. A short while ago compiling with nutika 4.0.1 and MSVC worked just fine. I then updated Visual Studio from 17.12.11 (or something like this) to 17.12.17 and it stopped working. Still isn't working on 17.12.18.

In an old Python 3.12 venv with nuitka 2.7.7 it works just fine!

But it doesn't on any of my Py 3.13 venvs with any nuitka 4.0.x...

With nuitka 4.0.1 i get the following, indicating a missing environment variable:

```
Nuitka-Scons:WARNING: Windows SDK must be installed in Visual Studio for it to be usable with Nuitka. Use the Visual
Nuitka-Scons:WARNING: Studio installer for adding it.
AttributeError: 'NoneType' object has no attribute 'startswith':
  File "C:\Daten\Repos\PLAYGR~1\nuitka\venv\Lib\SITE-P~1\nuitka\build\BACKEN~1.SCO", line 80:
    env = createNuitkaSconsEnvironment()
  File "C:\Daten\Repos\Playground\nuitka\venv\Lib\site-packages\nuitka\build\SconsCompilerSettings.py", line 1069:
    if env.the_compiler is None or getExecutablePath(env.the_compiler, env=env) is None:
  File "C:\Daten\Repos\Playground\nuitka\venv\Lib\site-packages\nuitka\build\SconsUtils.py", line 495:
    while filename.startswith("$"):
```

Newer nuitka specify that the "CC" variable is not set and that this should never happen:

```
FATAL: Error, scons environment variable 'CC' is not set, this ought to never happen. Please report the bug.
FATAL: Failed unexpectedly in Scons C backend compilation.
```

The various WindowsSDK variables are all set in my "Developer Powershell for VS 2022".

For now I am using zig, but I would like to keep the option to use MSVC as well.

**Comment by kayhayen** [comment]
@Ablinne Posting below closed or unrelated issues is a surefire way to get ignored. I am not going to guess without a fresh issue template, what kinds of mistakes and setup you have made, and I am not going to trace, or remember to check later, or searching for where something was said. Please open new issues for new issues. If the issue is closed, it's not the same even if the symptom looks similar to you.

**Comment by kayhayen** [comment]
Closing due to lack of feedback.
