### PR TITLE
MacOS standalone rpath issue (Feature/fix issue #499)

### PR DESCRIPTION
**Pull request by gioboske**
# What does this PR do?
Fix **standalone** (i.e. compiled with `--standalone` option) executable rpath (MacOS) for libpython.
For embedded-modules compilation (i.e. `--follow-imports` option) and extension module compilation (i.e. `--module` option), similar problems persist.

This is an hotfix (the issue affects also the `master` branch). Anyway, `develop` is selected as base branch, since the modules affected by this PR changed a lot from `master` to `develop`.

# Why was it initiated? Any relevant Issues?
Related to #499 (and #516).

# PR Checklist

- [x] Correct base branch selected? `develop` for new features and bug fixes too.
      If it's part of a hotfix, it will be moved to `master` during it.
- [ ] All tests still pass. Check the developer manual about `Running the Tests`.
      There are Travis tests that cover the most important things however, and you
      are welcome to rely on those, but they might not cover enough.
- [ ] Ideally new features or fixed regressions ought to be covered via new tests.
- [x] ~~Ideally new or changed features have documentation updates.~~ Not needed

### CODE REVIEW

**Comment by gioboske** [comment]
This PR seems to resolve the issue when try to compile on conda Python 3.7 with `--standalone` option.
Anyway the libpython is not statically linked. Static linking of libpython works in `--standalone` on conda Python 3.6, but it not works on conda Python 3.7.
To static link libpython on conda Python 3.7, the `nuitka.Options.shallUseStaticLibPython` shall be modified as described in #580 and PR #581 (due to changes of `sys.version` string in conda Python > 3.6).
However the compilation results in the following error:
```
Python: 3.7.5 from conda
OS: Darwin
Arch: x86_64
```

```
> python -m nuitka --standalone hello.py
duplicate symbol '_Py_GetArgcArgv' in:
    hello.build/MainProgram.o
    /Users/testuser/dev/miniconda3/envs/py37/lib/libpython3.7m.a(main.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [hello.dist/hello] Error 1
```

**Comment by kayhayen** [comment]
The criterion (being Anaconda) should probably be more generic, but this definitely helps. Thanks for your contribution!
