### ISSUE TITLE
Typo on RICH_COMPARE_BOOL_LT_INT_INT definition

### ISSUE THREAD

**Issue by TiboLGH** [Nuitka/Nuitka#221]
Hi,

While compiling my Python project with Nuitka 0.6.1, I hit a linker issue on 'RICH_COMPARE_BOOL_LT_INT_INT' symbol.
After quick check, it appears there is a typo in HelpersComparison.c on this symbol (introduced with commit 08246bb328b61fe326088c67fae6ef5995a44af9)

Proposed patch (not sure it is worth a pull request) :
```diff
diff --git a/nuitka/build/static_src/HelpersComparison.c b/nuitka/build/static_src/HelpersComparison.c
index 28c3694..0c290f8 100644
--- a/nuitka/build/static_src/HelpersComparison.c
+++ b/nuitka/build/static_src/HelpersComparison.c
@@ -1222,7 +1222,7 @@ int RICH_COMPARE_BOOL_GTE_OBJECT_INT(PyObject *operand1, PyObject *operand2) {
     return MY_RICHCOMPARE_BOOL(operand1, operand2, Py_GE);
 }

-int RICH_COMPARE_LT_BOOL_INT_INT(PyObject *operand1, PyObject *operand2) {
+int RICH_COMPARE_BOOL_LT_INT_INT(PyObject *operand1, PyObject *operand2) {
     assert(PyInt_CheckExact(operand1));
     assert(PyInt_CheckExact(operand2));
```

My setup : 
```
$  python -m nuitka --version
0.6.1
Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
Executable: C:\Python27\python.exe
OS: Windows
Arch: x86
```
Regards,
Thibault

**Comment by kayhayen** [comment]
Thanks for the report, I will make it part of the next (first) hotfix to be released.

**Comment by kayhayen** [comment]
It seems many more functions should be affected. I wonder why I wasn't seeing any of these being used so far.

**Comment by kayhayen** [comment]
Release as 0.6.1.1

**Comment by gittethis** [comment]
somehow this is still present in 0.6.1.1

`module.serial.serialposix.c:(.text+0x22148): undefined reference to RICH_COMPARE_BOOL_LT_INT_INT
collect2: error: ld returned 1 exit status
scons: *** [sms_handler_demo.bin] Error 1
`

`0.6.1.1
Python: 2.7.16 (default, Apr  6 2019, 01:42:57)
Executable: /usr/bin/python
OS: Linux
Arch: armv7l
`

correctable by applying the patch in the beginning of this thread (correcting the typo in  `/usr/lib/python2.7/dist-packages/nuitka/build/static_src/HelpersComparison.c`

**Comment by kayhayen** [comment]
This is an ancient release @gittethis use the latest stable one.
