### ISSUE TITLE
gRPC: cannot reuse already awaited __anext__()/asend()

### ISSUE THREAD

**Issue by paskozdilar** [Nuitka/Nuitka#3608]
## 🐛 Bug Description

Since the reproduction is not trivial and requires gRPC, I've created a repository for this:
[paskozdilar/nuitka-bug-report](https://github.com/paskozdilar/nuitka-bug-report)

For the general idea, this is the `main.py` file content:

```python3
#!/usr/bin/env python3

import asyncio
from grpc.aio import insecure_channel
from proto import test_pb2_grpc
from proto import test_pb2


async def main():
    while True:
        try:
            async for _ in listen():
                pass

        except Exception as exc:
            print("Exception:", exc, flush=True)
            await asyncio.sleep(1)


async def listen():
    async with insecure_channel("localhost:1234") as channel:
        stub = test_pb2_grpc.TestServiceStub(channel)
        async for message in stub.ServerStream(test_pb2.Request(data="foo")):
            yield message



if __name__ == '__main__':
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
```

When using gRPC server-streams, if connection fails, we except to get an `AioRpcError` exception with the following data printed:
```
<AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:1234: Failed to connect to remote
 host: connect: Connection refused (111)"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"failed to connect to all addr
esses; last error: UNKNOWN: ipv4:127.0.0.1:1234: Failed to connect to remote host: connect: Connection refused (111)"}"
```

However, if compiled with Nuitka, we get a different error:
```
cannot reuse already awaited __anext__()/asend()
```

It seems to have something to do with async generators, since if I remove the `listen()` method (please see reproduction code linked above) and just move the code inside main method directly, I don't get this issue.

### 1. Nuitka Version, Python Version, OS, and Platform

2.8rc14
Commercial: None
Python: 3.13.7 (main, Sep  8 2025, 22:53:40) [GCC 14.2.0]
Flavor: Unknown
GIL: yes
Executable: /usr/local/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 13
Version C compiler: /usr/bin/gcc (gcc 14).

### 2. How Nuitka and Python were Installed

pip inside python docker container

### 3. Relevant PyPI Packages and Versions

```
Package           Version Location                                Installer
----------------- ------- --------------------------------------- ---------
grpcio            1.75.0  /usr/local/lib/python3.13/site-packages pip
Nuitka            2.8rc14 /usr/local/lib/python3.13/site-packages pip
ordered-set       4.1.0   /usr/local/lib/python3.13/site-packages pip
pip               25.2    /usr/local/lib/python3.13/site-packages pip
protobuf          6.32.1  /usr/local/lib/python3.13/site-packages pip
typing_extensions 4.15.0  /usr/local/lib/python3.13/site-packages pip
zstandard         0.25.0  /usr/local/lib/python3.13/site-packages pip
```

```
Nuitka 2.8rc14 pip
grpcio 1.75.0 pip
ordered-set 4.1.0 pip
pip 25.2 pip
protobuf 6.32.1 pip
typing_extensions 4.15.0 pip
zstandard 0.25.0 pip
```

### 1. "Hello World" Test (if applicable)

Works

### 2. Short, Self-Contained, Correct, Eligible (SSCCE) Example

The smallest self-contained example I could create is uploaded here:
https://github.com/paskozdilar/nuitka-bug-report

### 3. Nuitka Command Line Options

```sh
python -m nuitka ./main.py
```

## 📉 Expected Behavior

Program prints gRPC error:

```
<AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:1234: Failed to connect to remote
 host: connect: Connection refused (111)"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_status:14, grpc_message:"failed to connect to all addr
esses; last error: UNKNOWN: ipv4:127.0.0.1:1234: Failed to connect to remote host: connect: Connection refused (111)"}"
```

## 📄 Actual Behavior & Output

Program prints asyncio exception:
```
cannot reuse already awaited __anext__()/asend()
```

**Comment by paskozdilar** [comment]
Not sure if this is related, but when building with `--follow-imports` flag, the program doesn't seem to work at all - I don't get any output whatsoever.
After 3 Ctrl+C hits, I get the following stack trace:
```
^C^C^CTraceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1898, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 110, in grpc._cython.cygrpc.shutdown_grpc_aio
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 114, in grpc._cython.cygrpc.shutdown_grpc_aio
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 79, in grpc._cython.cygrpc._actual_aio_shutdown
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 136, in grpc._cython.cygrpc.PollerComplet
ionQueue.shutdown
  File "/usr/lib/python3.11/threading.py", line 1087, in join
    def join(self, timeout=None):

KeyboardInterrupt
Exception ignored in: 'grpc._cython.cygrpc.AioChannel.__dealloc__'
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 110, in grpc._cython.cygrpc.shutdown_grpc_aio
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 114, in grpc._cython.cygrpc.shutdown_grpc_aio
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 79, in grpc._cython.cygrpc._actual_aio_shutdown
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 136, in grpc._cython.cygrpc.PollerComplet
ionQueue.shutdown
  File "/usr/lib/python3.11/threading.py", line 1087, in join
    def join(self, timeout=None):

KeyboardInterrupt: 
```

Seems like gRPC generally doesn't play nice with Nuitka...

**Comment by paskozdilar** [comment]
When building with `--standalone`, I also get no output - however, after only 2 Ctrl+C hits, I get a different stack trace:

```
^C^CTraceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 110, in grpc._cython.cygrpc.shutdown_grpc_aio
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 114, in grpc._cython.cygrpc.shutdown_grpc_aio
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 79, in grpc._cython.cygrpc._actual_aio_shutdown
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 131, in grpc._cython.cygrpc.PollerComplet
ionQueue.shutdown
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 69, in grpc._cython.cygrpc._BoundEventLoo
p.close
  File "/home/ext_zdilap/stuff/python/test/main.dist/asyncio/selector_events.py", line 346, in remove_reader
  File "/home/ext_zdilap/stuff/python/test/main.dist/asyncio/runners.py", line 157, in _on_sigint
KeyboardInterrupt
Exception ignored in: 'grpc._cython.cygrpc.AioChannel.__dealloc__'
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 110, in grpc._cython.cygrpc.shutdown_grpc_aio
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 114, in grpc._cython.cygrpc.shutdown_grpc_aio
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 79, in grpc._cython.cygrpc._actual_aio_shutdown
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 131, in grpc._cython.cygrpc.PollerComplet
ionQueue.shutdown
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 69, in grpc._cython.cygrpc._BoundEventLoo
p.close
  File "/home/ext_zdilap/stuff/python/test/main.dist/asyncio/selector_events.py", line 346, in remove_reader
  File "/home/ext_zdilap/stuff/python/test/main.dist/asyncio/runners.py", line 157, in _on_sigint
KeyboardInterrupt: 
```

**Comment by kayhayen** [comment]
Accelerated mode is not allowed to include many packages that mix compiled and uncompiled code, which happens easily in that case, so that's not relevant. The not at all following code, which should have given you a warning, ought to still  work. 

It might indicate an incompatibly in the uncompiled generator integration with Python 3.13, which totally may be overall issue for all modes. Can you confirm or deny that it works with Python3.12?

**Comment by paskozdilar** [comment]
> Can you confirm or deny that it works with Python3.12?

I assume you mean the second issue (with `--follow-imports`)?

When I tried compiling in Python3.12 venv (installed by `uv venv --python=3.12`), the example program didn't run at all, it only printed a stack trace with `AttributeError: module 'grpc._cython.cygrpc' has no attribute 'BaseEvent'`.
I tried using apt version, and running it in docker container, and the same issue happens.

I've updated the [paskozdilar/nuitka-bug-report](https://github.com/paskozdilar/nuitka-bug-report) repository for easier reproduction.

Here's the full stack trace:
```
$ PYTHON_VERSION=3.12 docker compose build with-nuitka-follow && docker compose up with-nuitka-follow
[build logs...]
with-nuitka-follow-1  | Traceback (most recent call last):
with-nuitka-follow-1  |   File "/app/main.py", line 5, in <module>
with-nuitka-follow-1  |     from grpc.aio import insecure_channel
with-nuitka-follow-1  |
with-nuitka-follow-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
with-nuitka-follow-1  |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
with-nuitka-follow-1  |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
with-nuitka-follow-1  |   File "/usr/local/lib/python3.12/site-packages/grpc/__init__.py", line 22, in <module grpc>
with-nuitka-follow-1  |     from grpc import _compression
with-nuitka-follow-1  |
with-nuitka-follow-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
with-nuitka-follow-1  |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
with-nuitka-follow-1  |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
with-nuitka-follow-1  |   File "/usr/local/lib/python3.12/site-packages/grpc/_compression.py", line 21, in <module grpc._compression>
with-nuitka-follow-1  |     from grpc._typing import MetadataType
with-nuitka-follow-1  |
with-nuitka-follow-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
with-nuitka-follow-1  |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
with-nuitka-follow-1  |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
with-nuitka-follow-1  |   File "/usr/local/lib/python3.12/site-packages/grpc/_typing.py", line 45, in <module grpc._typing>
with-nuitka-follow-1  |     UserTag = Callable[[cygrpc.BaseEvent], bool]
with-nuitka-follow-1  |
with-nuitka-follow-1  | AttributeError: module 'grpc._cython.cygrpc' has no attribute 'BaseEvent'
with-nuitka-follow-1 exited with code 1
```

> Accelerated mode is not allowed to include many packages that mix compiled and uncompiled code

Does this mean that accelerated mode is generally not expected to work with compiled Python imports, such as grpcio?

**Comment by paskozdilar** [comment]
When compiled with `--standalone`, I again get no output, and similar stack trace to the second issue:

```
$ ./main.dist/main.bin
Python 3.12.11 (main, Jun  4 2025, 08:56:18) [GCC 11.4.0]
^C^C^CTraceback (most recent call last):
  File "~/stuff/python/test/main.dist/asyncio/runners.py", line 195, in run
  File "~/stuff/python/test/main.dist/asyncio/runners.py", line 118, in run
  File "~/stuff/python/test/main.dist/asyncio/base_events.py", line 678, in run_until_complete
  File "~/stuff/python/test/main.dist/asyncio/base_events.py", line 645, in run_forever
  File "~/stuff/python/test/main.dist/asyncio/base_events.py", line 1961, in _run_once
  File "~/stuff/python/test/main.dist/selectors.py", line 468, in select
  File "~/stuff/python/test/main.dist/asyncio/runners.py", line 157, in _on_sigint
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 110, in grpc._cython.cygrpc.shutdown_grpc_aio
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 114, in grpc._cython.cygrpc.shutdown_grpc_aio
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 79, in grpc._cython.cygrpc._actual_aio_shutdown
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 131, in grpc._cython.cygrpc.PollerCompletionQueue.shutdown
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 69, in grpc._cython.cygrpc._BoundEventLoop.close
  File "/home/ext_zdilap/stuff/python/test/main.dist/asyncio/selector_events.py", line 359, in remove_reader
KeyboardInterrupt
Exception ignored in: 'grpc._cython.cygrpc.AioChannel.__dealloc__'
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 110, in grpc._cython.cygrpc.shutdown_grpc_aio
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 114, in grpc._cython.cygrpc.shutdown_grpc_aio
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 79, in grpc._cython.cygrpc._actual_aio_shutdown
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 131, in grpc._cython.cygrpc.PollerCompletionQueue.shutdown
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/completion_queue.pyx.pxi", line 69, in grpc._cython.cygrpc._BoundEventLoop.close
  File "/home/ext_zdilap/stuff/python/test/main.dist/asyncio/selector_events.py", line 359, in remove_reader
KeyboardInterrupt:
```

I've also added an example to bug-report repo.

**Comment by kayhayen** [comment]
I am not interested in other modes than standalone for this issue at this time, and thanks for confirming this is not 3.13 specific. I will look into it.
