### ISSUE TITLE
pywebview support

### ISSUE THREAD

**Issue by paulzzh** [Nuitka/Nuitka#3251]
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.
```
2.5.6
Commercial: None
Python: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
Flavor: CPython Official
Executable: E:\Documents\python\DomManipulation\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: D:\.nuitka\downloads\gcc\x86_64\14.2.0posix-19.1.1-12.0.0-msvcrt-r2\mingw64\bin\gcc.exe (gcc 14.2.0)
```
- How did you install Nuitka and Python
```
Install python 3.11 with windows installer downloaded from python.org
Create a new venv and install Nuitka with python -m pip install nuitka
```
- The specific PyPI names and versions
```
(DomManipulation) E:\Documents\python\DomManipulation>python -m pip list -v
Package           Version Location                                              Installer
----------------- ------- ----------------------------------------------------- ---------
bottle            0.13.2  E:\Documents\python\DomManipulation\Lib\site-packages pip
cffi              1.17.1  E:\Documents\python\DomManipulation\Lib\site-packages pip
clr-loader        0.2.6   E:\Documents\python\DomManipulation\Lib\site-packages pip
Nuitka            2.5.6   E:\Documents\python\DomManipulation\Lib\site-packages pip
ordered-set       4.1.0   E:\Documents\python\DomManipulation\Lib\site-packages pip
pip               24.0    E:\Documents\python\DomManipulation\Lib\site-packages pip
proxy_tools       0.1.0   E:\Documents\python\DomManipulation\Lib\site-packages pip
pycparser         2.22    E:\Documents\python\DomManipulation\Lib\site-packages pip
pythonnet         3.0.4   E:\Documents\python\DomManipulation\Lib\site-packages pip
pywebview         5.3.2   E:\Documents\python\DomManipulation\Lib\site-packages pip
setuptools        65.5.0  E:\Documents\python\DomManipulation\Lib\site-packages pip
typing_extensions 4.12.2  E:\Documents\python\DomManipulation\Lib\site-packages pip
zstandard         0.23.0  E:\Documents\python\DomManipulation\Lib\site-packages pip

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
```
- Many times when you get an error from Nuitka, your setup may be special
```
pywebview example code not work.
```
- Also supply a Short, Self Contained, Correct, Example
https://pywebview.flowrl.com/examples/dom_manipulation.html
```
import random
import webview

def bind(window):
    toggle_button = window.dom.get_element('#toggle-button')
    toggle_button.events.click += lambda e: print("events should not be NoneType.") # Exception here.

if __name__ == '__main__':
    window = webview.create_window(
        'DOM Manipulations Example', html='''
            <html>
                <head>
                <style>
                    button {
                        font-size: 100%;
                        padding: 0.5rem;
                        margin: 0.3rem;
                        text-transform: uppercase;
                    }
                    .container {
                        display: flex;
                        flex-wrap: wrap;
                    }
                </style>
                </head>
                <body>
                    <button id="toggle-button">Toggle circle</button>
                </body>
            </html>
        '''
    )
    webview.start(bind, window, debug=True)
```
- Provide in your issue the Nuitka options used
```
(DomManipulation) E:\Documents\python\DomManipulation>python -m nuitka --mingw64 --standalone run.py --windows-console-mode=force
Nuitka-Options: Used command line options: --mingw64 --standalone run.py --windows-console-mode=force
Nuitka: Starting Python compilation with Nuitka '2.5.6' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Non downloaded winlibs-gcc 'D:\GreenPrograms\mingw64\bin\gcc.exe' is being ignored, Nuitka is very
Nuitka-Scons: dependent on the precise one.
Nuitka-Scons: Backend C compiler: gcc (gcc 14.2.0).
Nuitka-Scons: Backend linking program with 63 files (no progress information available for this stage).
Nuitka-Scons: Compiled 63 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 58
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 5
Nuitka-Plugins:dll-files: Found 1 file DLLs from clr_loader.ffi installation.
Nuitka-Plugins:dll-files: Found 4 files DLLs from webview installation.
Nuitka-Plugins:data-files: Included data file 'pythonnet\runtime\Python.Runtime.dll' due to package data for
Nuitka-Plugins:data-files: 'pythonnet'.
Nuitka-Plugins:data-files: Included data file 'webview\lib\pywebview-android.jar' due to package data directory 'lib'
Nuitka-Plugins:data-files: for 'webview'.
Nuitka: Keeping build directory 'run.build'.
Nuitka: Successfully created 'run.dist\run.exe'.
```
- Program output to console
```
[pywebview] Using WinForms / Chromium
Exception in thread Thread-1 (bind):
Traceback (most recent call last):
  File "E:\Documents\python\DomManipulation\run.dist\threading.py", line 1045, in _bootstrap_inner
  File "E:\Documents\python\DomManipulation\run.dist\threading.py", line 982, in run
  File "E:\Documents\python\DomManipulation\run.dist\run.py", line 15, in bind
AttributeError: 'NoneType' object has no attribute 'events'
```
- Note if this is a regression

  If it used to work in an earlier version of Nuitka, please note what you know about that. Since
  git bisect is a thing for which we do a lot of error to make it usable, this will help
  dramatically to isolate the issue.
```
Also tried Nuitka 2.4.11 & gcc 13.2.0. Not work.
--onefile not work.
--standalone not work.
`python run.py` works and print `events should not be NoneType.`
```
```
Can not found `pywebview` values in devtools console. It should be there.
Every dom should has a `data-pywebview-id` attr to make `get_element()` works.
```
https://github.com/r0x0r/pywebview/blob/dddaa76e71f8a02d56e0edcf0dfaa4350d5962b8/webview/dom/dom.py#L51

**Comment by paulzzh** [comment]
It seems fixed with `--include-data-dir=Lib\site-packages\webview\js=webview\js`
https://github.com/r0x0r/pywebview/issues/1509

**Comment by kayhayen** [comment]
Good job, going to re-open it until I release it as a hotfix.

**Comment by kayhayen** [comment]
@paulzzh just to make you aware, --include-package-data is an easier choice, such that you don't have to find the file origin yourself, but good job on the report and PR. I will be part of the 2.5.7 hotfix for sure.

**Comment by kayhayen** [comment]
Part of the 2.5.7 release I just made.
