### ISSUE TITLE
Error running standalone executable with ZeroMQ dependency.

### ISSUE THREAD

**Issue by jackz314** [Nuitka/Nuitka#955]
I'm trying to deploy with the `--standalone` option, my code uses ZeroMQ (`pyzmq`), and when I run the output exe from nuitka, the following error appears:

```
Traceback (most recent call last):
  File "C:\Users\zhang\OneDrive\Desktop\Projects\ML\tmp\Z89BA~1.DIS\z.py", line 1, in <module>
  File "C:\Users\zhang\OneDrive\Desktop\Projects\ML\tmp\Z89BA~1.DIS\zmq\__init__.py", line 55, in <module zmq>
  File "C:\Users\zhang\OneDrive\Desktop\Projects\ML\tmp\Z89BA~1.DIS\zmq\backend\__init__.py", line 40, in <module zmq.backend>
  File "C:\Users\zhang\OneDrive\Desktop\Projects\ML\tmp\Z89BA~1.DIS\zmq\utils\sixcerpt.py", line 34, in reraise
  File "C:\Users\zhang\OneDrive\Desktop\Projects\ML\tmp\Z89BA~1.DIS\zmq\backend\__init__.py", line 27, in <module zmq.backend>
  File "C:\Users\zhang\OneDrive\Desktop\Projects\ML\tmp\Z89BA~1.DIS\zmq\backend\select.py", line 28, in select_backend
  File "C:\Users\zhang\OneDrive\Desktop\Projects\ML\tmp\Z89BA~1.DIS\zmq\backend\cython\__init__.py", line 6, in <module zmq.backend.cython>
ImportError: LoadLibraryExW 'C:\Users\zhang\OneDrive\Desktop\Projects\ML\tmp\Z89BA~1.DIS\zmq\backend\cython\error.pyd' failed: The specified module could not be found.
```
I installed nuitka via pip (without virtual-env). Below is the result from `python -m nuitka --version`:
```
0.6.11.2
Python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
Executable: C:\Program Files\Python38\python.exe
OS: Windows
Arch: x86_64
```

And this is the command I used to build the exe:
```
python -m nuitka --plugin-enable=pylint-warnings --show-progress --show-scons --standalone .\z.py
```

My `pyzmq` version is 20.0.0, and below is a minimum example code that you can use to reproduce this issue:
```python
import zmq
s = zmq.Context().socket(zmq.SUB)
s.connect("tcp://127.0.0.1:10290")
s.setsockopt(zmq.SUBSCRIBE, b"")
while True:
    msg = s.recv_string()
    print(msg)
    if msg == "exit": break
```

**Comment by kayhayen** [comment]
This also affects zmq 21.0.2 as well, and it's a Windows only issue it seems.

**Comment by kayhayen** [comment]
Something they are doing in Cython compiled `zmq.backends.cython.error` loads the `zmq.libzmq` extension module, but with a filename that seems hard coded and from a spot that is not its package.

**Comment by kayhayen** [comment]
This is working on factory and will appear in the next hotfix. https://nuitka.net/doc/factory.html

**Comment by jackz314** [comment]
I just tried out the factory branch, and it seems to work now. However, when the code exits, the following error appears (which doesn't happen when running the code normally):
```
Exception ignored in: <compiled_function Socket.__del__ at 0x0000000011B108B0>
Traceback (most recent call last):
  File "C:\Users\zhang\OneDrive\Desktop\Projects\ML\tmp\Z89BA~1.DIS\zmq\sugar\socket.py", line 68, in __del__
  File "C:\Users\zhang\OneDrive\Desktop\Projects\ML\tmp\Z89BA~1.DIS\zmq\sugar\socket.py", line 122, in close
RuntimeError: super(): __class__ is not a type (NoneType)
Exception ignored in: <compiled_function Context.__del__ at 0x0000000011B28C70>
Traceback (most recent call last):
  File "C:\Users\zhang\OneDrive\Desktop\Projects\ML\tmp\Z89BA~1.DIS\zmq\sugar\context.py", line 54, in __del__
  File "C:\Users\zhang\OneDrive\Desktop\Projects\ML\tmp\Z89BA~1.DIS\zmq\sugar\context.py", line 154, in term
RuntimeError: super(): __class__ is not a type (NoneType)
```

I'm not sure if this is still a zmq issue, but it seems to originate from the zmq socket's destructor.

**Comment by jackz314** [comment]
I'm not sure if this is a separate issue, but after upgrading pyzmq to 21.0.2, I can't build the same code using nuitka anymore, the following error appears when building (this is while compiling I believe):

```
scons: building `module.scipy.sparse.linalg.eigen.o' because it doesn't exist
C:\Users\zhang\AppData\Local\Nuitka\Nuitka\ccache\v3.7.12\ccache.exe "C:\Users\zhang\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5\mingw64\bin\gcc.exe" -o module.scipy.sparse.linalg.eigen.o -c -std=c11 -fvisibility=hidden -fwrapv -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -fcompare-debug-second -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_STANDALONE -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=165 -D_NUITKA_EXE "-IC:\Program Files\Python38\include" -I. -IC:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\include -IC:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\static_src module.scipy.sparse.linalg.eigen.c
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
                                                                                                                                                                    scons: *** [module.scipy.sparse.linalg.eigen.o] AttributeError : 'NoneType' object has no attribute 'unit'
Nuitka-Scons:INFO: Running 'C:\\Users\\zhang\\AppData\\Local\\Nuitka\\Nuitka\\ccache\\v3.7.12\\ccache.exe "C:\\Users\\zhang\\AppData\\Local\\Nuitka\\Nuitka\\gcc\\x86_64\\10.2.0-11.0.0-8.0.0-r5\\mingw64\\bin\\gcc.exe" -o "module.scipy.signal.signaltools.o" -c -std=c11 -fvisibility=hidden -fwrapv -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -fcompare-debug-second -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_STANDALONE -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=165 -D_NUITKA_EXE "-IC:\\Program Files\\Python38\\include" -I. -IC:\\PROGRA~1\\Python38\\lib\\SITE-P~1\\nuitka\\build\\include -IC:\\PROGRA~1\\Python38\\lib\\SITE-P~1\\nuitka\\build\\static_src "module.scipy.signal.signaltools.c"' took 60.42 secondsscons: internal stack trace:
  File "C:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-3.1.2\SCons\Job.py", line 258, in run
    task.execute()

  File "C:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-3.1.2\SCons\Script\Main.py", line 206, in execute
    SCons.Taskmaster.OutOfDateTask.execute(self)

  File "C:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-3.1.2\SCons\Taskmaster.py", line 270, in execute                                          Traceback (most recent call last):
  File "C:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-3.1.2\SCons\Taskmaster.py", line 255, in execute               | 0/1656 [00:00<?, ?file/s]
  File "C:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-3.1.2\SCons\Node\__init__.py", line 766, in build
    self.get_executor()(self, **kw)
  File "C:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-3.1.2\SCons\Executor.py", line 397, in __call__
  File "C:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-3.1.2\SCons\Executor.py", line 128, in execute_action_list
    status = act(*args, **kw)
  File "C:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-3.1.2\SCons\Action.py", line 1052, in __call__
  File "C:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-3.1.2\SCons\Action.py", line 1120, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "C:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-3.1.2\SCons\Action.py", line 708, in __call__
  File "C:\PROGRA~1\Python38\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-3.1.2\SCons\Action.py", line 952, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "C:\Program Files\Python38\lib\site-packages\nuitka\build\SconsSpawn.py", line 125, in spawnWindowsCommand
    data, err, rv = runProcessMonitored(cmdline, env)
  File "C:\Program Files\Python38\lib\site-packages\nuitka\build\SconsSpawn.py", line 89, in runProcessMonitored
    updateSconsProgressBar()
scons: building terminated because of errors.ckages\nuitka\build\SconsProgress.py", line 56, in updateSconsProgressBar
AttributeError: 'NoneType' object has no attribute 'unit'
```
I'm not sure if this is because of an update in pyzmq, scipy (based on the error output), or something else.

**Comment by kayhayen** [comment]
There is a breakage from the progress bar, use could always use `--no-progressbar` for the time being. I am assuming, this is from older factory code? @jackz314 is that true, the code somehow isn't the latest one I think.

Also the other issue with the destructor seems interesting, but your reproducer didn't exit, so I think I couldn't see it with that, can you provide an updated one?

**Comment by jackz314** [comment]
zmq blocks until a message is received, so you can either send an exit message ("exit") to the 10290 port, or just remove everything after `s.connect()`, the destructor should still be called in this case:

```python
import zmq
s = zmq.Context().socket(zmq.SUB)
s.connect("tcp://127.0.0.1:10290")
```

**Comment by kayhayen** [comment]
@jackz314 the super thing is an indetermism, I am not getting it everywhere, it happens during the cleanup, where the zmq code is making a function call inside `__del__` that relies on module variables, but they are set to `None` during finalization. So it may or may not happen.

The incompatibility of Nuitka here, is that we use one code for all forms of `super()` but the error is actually only supposed to be given, if the form of `super` without arguments were called, which is not the case here. It seems that at least starting with some Python version, there might be this behaviour changed or it never was like that.

For now it will be safe to ignored, because well, that is what it is right now. For Nuitka, we can add optimization to diversify the variants with different argument numbers, and make sure to only check what we are supposed to check in the different implementations. That's not too hard, but definitely not necessarily in the next hotfix.

**Comment by kayhayen** [comment]
So this is in 0.6.11.5 hotfix

**Comment by kayhayen** [comment]
Improvements to `super` that should make it more compatible are in the develop and will be in the next release that should follow soon.

**Comment by kayhayen** [comment]
Part of the 0.6.12 release.
