### ISSUE TITLE
`_IncompleteInputError` causes a compilation error

### ISSUE THREAD

**Issue by ZeroIntensity** [Nuitka/Nuitka#4049]
Using the (internal) `_IncompleteInputError` builtin results in a compilation error when used with Nuitka:

```py
try:
    raise _IncompleteInputError
except _IncompleteInputError:
    print(123)
```

```
module.__main__.c: In function 'module_code___main__':
module.__main__.c:505:26: error: 'PyExc__IncompleteInputError' undeclared (first use in this function); did you mean 'PyExc_IncompleteInputError'?
  505 | tmp_raise_type_input_1 = PyExc__IncompleteInputError;
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          PyExc_IncompleteInputError
module.__main__.c:505:26: note: each undeclared identifier is reported only once for each function it appears in
```

Found while working on the 3.13 test suite.

**Comment by kayhayen** [comment]
Sourcery was right about the tuple code would not have worked. Sort for bad case of code duplication that I elminited, now `(_IncompleteError)` is usable too, some exception catches and what not can do this. I am closing this one early for lack of general relevance, although it's a stdlib file using it I think, but currently we don't fully care about that I think.
