### ISSUE TITLE
Cannot import `metadata` from `importlib` by Nuitka 0.7 with `--standalone`

### ISSUE THREAD

**Issue by Hintay** [Nuitka/Nuitka#1443]
Hello, I recently tried Nuitka 0.7, but had an issue with compiling the script that use `importlib`.

Here is a small exmple:
```python
from importlib import metadata

print(metadata)
```

Use the following command with Nuitka 0.7:
```shell
nuitka --mingw64 --lto=no --follow-imports --standalone importlib_test.py
```

There will be a `ImportError` after running it.
```
Traceback (most recent call last):
  File "importlib_test.py", line 1, in <module>
ImportError: cannot import name 'metadata' from 'importlib' (unknown location)
```

It looks like the `importlib` was not fully packed, as this script works if I don't use the stand-alone mode. Also, this script works with Nuitka 0.6.19.7 and `--standalone`.
```
<module 'importlib.metadata' from 'C:\\Users\\Hintay\\.conda\\lib\\importlib\\metadata.py'>
```

Environments:
- Python 3.8.12 x86_64 in Miniconda
- Nuitka 0.7
- Windows 11 21H2

**Comment by kayhayen** [comment]
Man, these guys want to make sure they include all of standard library. It needs  `email` module, but that is hidden dependencies these days and not included automatically. I added it on factory, and it will be in the first hotfix. 

Part of the issue that we no longer include these modules by default.

**Comment by kayhayen** [comment]
Part of 0.7.1 hotfix I just made. The assumption that `email` is rare as a hidden dependency didn't hold up very long. :)
