### ISSUE TITLE
Python 3.12 style class generics raises a TypeError when using subclasses.

### ISSUE THREAD

**Issue by MrEarle** [Nuitka/Nuitka#3812]
# Bug Report

## 🐛 Bug Description

When using the Python 3.12 generic class syntax (PEP 695) in a compiled module, subclasses fail to accept the correct number of type parameters at runtime.

Specifically, if a subclass defines fewer type parameters than its base class, the compiled version incorrectly enforces the parameter count of the base class instead of its own. In the provided example:

- `Base[T, V]` defines two parameters.

- `Sub[T]` inherits from `Base` defines one parameter, while specifying a concrete type for the other.

Result: Attempting to use `Sub[int]` (one argument) raises a `TypeError` stating that two arguments were expected.

The expected behavior is for `Sub[T]` to only require the single parameter defined in its signature.

### 1. Nuitka Version, Python Version, OS, and Platform

```
4.0.4
Commercial: None
Python: 3.12.12 (main, Jan 14 2026, 12:57:50) [Clang 17.0.0 (clang-1700.6.3.2)]
Flavor: pyenv
Executable: ~/Repos/obfuscation-test/.venv/bin/python
OS: Darwin
Arch: arm64
macOSRelease: 26.3.1
Version C compiler: clang (clang 17.0.0).
```

I also reproduced this issue in a docker container with linux runtime.

### 2. How Nuitka and Python were Installed

Python was installed with pyenv and nuitka with poetry.

Inside the docker container, python was installed from a base image, and nuitka with poetry.

### 3. Relevant PyPI Packages and Versions

No specific pagkages.

### 1. "Hello World" Test (if applicable)

I can compile and run without issue when not using Python 3.12 generics style syntax.

### 2. Short, Self-Contained, Correct, Eligible (SSCCE) Example

```python
# my_package.py
class Base[T, V]: ...
class Sub[T](Base[T, str]): ...
```

```python
# main.py
from my_package import Sub

sub = Sub[int]()
```

I compiled `my_package.py` then run `main.py` with only the compiled code in the path.

### 3. Nuitka Command Line Options

```sh
python -m nuitka --module --output-dir=. my_package.py
mv my_package.py another_name.py
python main.py
```

## 📉 Expected Behavior

I expect the code to run without issues. For the example I gave, it should run without exceptions, and no output should be visible.

## 📄 Actual Behavior & Output

```
Traceback (most recent call last):
  File "/Users/benjaminearle/Repos/obfuscation-test/main.py", line 3, in <module>
    sub = Sub[int]()
          ~~~^^^^^
  File "/Users/benjaminearle/.pyenv/versions/3.12.12/lib/python3.12/typing.py", line 398, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/benjaminearle/.pyenv/versions/3.12.12/lib/python3.12/typing.py", line 1110, in _generic_class_getitem
    _check_generic(cls, params, len(cls.__parameters__))
  File "/Users/benjaminearle/.pyenv/versions/3.12.12/lib/python3.12/typing.py", line 304, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments for {cls};"
TypeError: Too few arguments for <class 'package.Sub'>; actual 1, expected 2
```

## ↩️ Regression 

I haven't been able to get Python 3.12 generics syntax working on any version >= 4.0.0. I know you have been making many fixes, so I'm reporting this new error I'm seeing.

**Comment by kayhayen** [comment]
Thanks that's a good report, I don't think this ever worked, since we do generics only for so long, and when we did, with some clear mistakes.

**Comment by ZeroIntensity** [comment]
This is fixed now. I don't know if the fix has been released though.

**Comment by kayhayen** [comment]
He is using old Nuika.
