### ISSUE TITLE
AttributeError: 'nuitka_resource_reader_files' object has no attribute 'suffix'

### ISSUE THREAD

**Issue by Tapanhaz** [Nuitka/Nuitka#3055]
The said error occured when we run nuitka compiled exe . Here the code uses pathlib Path.
```
if file_path.is_file() and file_path.suffix == ".svg":

AttributeError: 'nuitka_resource_reader_files' object has no attribute 'suffix'
```

Not able to use file_path.match("*.svg") too. That also produces same kind of error.

2.4.2
Commercial: None
Python: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\N312\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Nuitka-Scons: For Python version 3.12 MSVC 14.3 or later is required, not 14.2 which is too old.
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by Tapanhaz** [comment]
> Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

Thanks. It is working on factory branch (2.5rc4).

**Comment by kayhayen** [comment]
Part of the current hotfix release 2.4.9
