### ISSUE TITLE
Nuitka fails to install with poetry and python > 3.9

### ISSUE THREAD

**Issue by eginez** [Nuitka/Nuitka#2174]
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/Nuitka/Nuitka/blob/develop/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed ✔️ 

* Please check out if the develop version of Nuitka works better for you. ✔️ 

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

```
❯ python -m nuitka --version
1.5.5
Commercial: None
Python: 3.10 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11)
Flavor: Anaconda Python
Executable: /Users/user/miniforge3/envs/project/bin/python
OS: Darwin
Arch: arm64
```

* How did you install Nuitka and Python
Via poetry
```
❯ poetry --version
Poetry (version 1.4.2)
```

```
❯ poetry show nuitka
 name         : nuitka
 version      : 1.5.5
 description  : Python compiler with full language support and CPython compatibility

dependencies
 - orderedset >=2.0.3
 - subprocess32 *
```

When installing the package, the package fails to build `orderset`, with the error below.

```
lib/orderedset/_orderedset.c:17344:19: error: call to undeclared function '_PyGen_Send'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
              ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                    ^
  lib/orderedset/_orderedset.c:17344:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
              ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  lib/orderedset/_orderedset.c:17349:19: error: call to undeclared function '_PyGen_Send'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
              ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                    ^
  lib/orderedset/_orderedset.c:17349:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
              ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  lib/orderedset/_orderedset.c:17433:19: error: call to undeclared function '_PyGen_Send'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
              ret = _PyGen_Send((PyGenObject*)yf, NULL);
                    ^
  lib/orderedset/_orderedset.c:17433:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
              ret = _PyGen_Send((PyGenObject*)yf, NULL);
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  17 warnings and 3 errors generated.
  error: command '/usr/bin/clang' failed with exit code 1
```

orderset is no longer supported and it does not build on python > 3.9.

**Comment by kayhayen** [comment]
I think this is a bug report for poetry. The subprocess32 is specified in setup.py like this:

```
if sys.version_info[:2] == (2, 7):
    install_requires.append("subprocess32")
```

And in `requirements.txt` as follows:

```
# More capable subprocess.
subprocess32; python_version == '2.7'
```

And in `requirements-devel.txt` as follows:

```
# Make testing more reliable on Python2 with timeout features added.
subprocess32 == 3.5.4 ; python_version == '2.7'
```

For `ordered-set` and `orderedset` similar things are going on. I do not think that I can do anything about it.

**Comment by tachikoma-li** [comment]
In case this might help, I think poetry try to resolve the dependencies of Nuitka by reading `requires.txt` from the `Nuitka.egg-info` folder after downloading `Nuitka-1.5.6.tar.gz` from PyPI. It seems that `requires.txt` doesn't have those python-specified versions as in `requirements.txt`, then poetry will try to install `subprocess32` and  `orderedset` regardless of platform and python version.
Would it be possible to also specify the constraints for `orderedset` and `subprocess32` in `requires.txt`?

**Comment by kayhayen** [comment]
I had no clue where `requires.txt` is coming from, but I find it in the `sdist` indeed. Nuitka makes its PyPI upload via public code https://github.com/Nuitka/Nuitka/blob/develop/nuitka/tools/release/pypi/__main__.py

This is run on an ARM Linux machine. I have no idea how, on earth, it would include the set of dependencies that match Python2 and Windows. I do not even know what this file is allowed to contain. Maybe it is making guesses from supported OSes and Python versions, or something. Needs research, but clearly *is* some sort of Nuitka bug indeed. I don't think anything but poetry is using it, though, at least people were happy with the requirements added to pull in `zstandard`, but maybe I was wrong. But they probably also use the standard wheel build, and poetry maybe not.

**Comment by kayhayen** [comment]
Rather than finding out, if having environment markers there, will break things, I am going to delete the file causing it. Nuitka is pretty usable even without installing these dependencies that it lists. I somehow believe this must be a change in poetry. My googling said, that source distributions are not very standardized. Poetry not using my `setup.py` is an interesting choice. I do not really want to add a third way of specifying requirements. Maybe they will fall back to the requirements.txt file.

For now this is a bit too hard to test for me and know if poetry does work the same on URLs too. So I am including that for the next hotfix release, and lets hope for the best. While at it, I am also enforcing to check it in Python2 and Python3 venv, because apparently the script happens to be run with Python2 right now, and OS environment markers are just ignored. When ran with Python3.10 it would create different ones, which of course wouldn't work with 3.7 e.g. and as such this is very annoying.

I was wondering, if a dependency on setuptools would haved sort of "solved" it as well. But the underlying issue of this file being wrong will remain. For me, the sdist is only there to run "install" or "wheel" targets on "setup.py" and nothing else.

**Comment by kayhayen** [comment]
So, I just added the testing with 3.10 and 2.7 to the PyPI upload (it was just using the one it was launched with) and both install their dependencies still properly if done with pip. Seems ready for the next hotfix too.

**Comment by radoering** [comment]
To fully support poetry e09d9918568fb78e37aa67e8130bbdac6e7843dd probably had to be reverted. See https://github.com/python-poetry/poetry/issues/7783#issuecomment-1501933870 for details.

Poetry expects that each wheel provides the same dependencies (including environment markers). If that's not the case, you can probably only define [multiple-constraints](https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies) with correct environment markers [referencing the wheels directly](https://python-poetry.org/docs/dependency-specification/#url-dependencies).

**Comment by kayhayen** [comment]
Are you saying that the `requires.txt` is not what is used by poetry after all?

**Comment by kayhayen** [comment]
Nuitka is being used with very old Python versions, as far back as things on CentOS 5 and Windows XP. That may seem crazy to you, but even CentOS 6 is a frequent target still. I am striving to keep the installation common. If there is a way to detect poetry using it, I would just empty the requirements, making it happy should that be a problem. Like I said, they are in no way mandatory, just nice to have them, so e.g. onefile just works with compression and ordered-set is just there.

The orderedset/ordered-set has to be version specific, simply because there is none that supports all versions. One of these days, I will check and see if poetry still has an issue now. I don't know why it would. Is it because poetry itself runs with a different version when extracting the requirements, maybe. But since 3.7 is a breaking point only, wouldn't that mean you use poetry with an old version, while running it on a newer one.

I recently lost my coverage from OBS for older setuptools. I used to be able to test on very ancient systems and now need to replace it with podman on my own. Once I restore it, I might feel comfortable with doing the strange kind of revert, where for newer setuptools one thing is done, and for older, it is not. But I would like to really avoid it, until such time that default pip installs have an issue.

**Comment by kayhayen** [comment]
From reading the issue, it also appears that `setup.py` is not used by poetry, which is fine. I am making sure that the `sdist` target is rather independent of the context. The criticized `install_requires` exception is now going to be hidden, so I would assume it will become good after next hotfix release. Since I do not upload development releases, we will have to wait until the hotfix is out to know for sure.

**Comment by radoering** [comment]
I just noticed that there are no wheels but just an sdist on PyPI. Thus, the last sentences in my previous post don't apply.

These should be the relevant lines:

- https://github.com/python-poetry/poetry/blob/b1fcfc02014f306a0b55a99829670de4d67b22a3/src/poetry/inspection/info.py#L282
- https://github.com/python-poetry/poetry/blob/b1fcfc02014f306a0b55a99829670de4d67b22a3/src/poetry/inspection/info.py#L249-L255

```
>>> pkginfo.SDist("Nuitka-1.5.6.tar.gz").requires_dist
()
```

Thus, a `requires.txt` will probably help. Sorry for the confusion.

There are several fallback levels. As it seems https://github.com/Nuitka/Nuitka/commit/e09d9918568fb78e37aa67e8130bbdac6e7843dd is only relevant if there is no `requires.txt`.

**Comment by radoering** [comment]
> To fully support poetry [e09d991](https://github.com/Nuitka/Nuitka/commit/e09d9918568fb78e37aa67e8130bbdac6e7843dd) probably had to be reverted.

Rethinking about it, this statement probably still remains true to a certain extent.

A `requires.txt` in the sdist might be sufficient if a package index (such as PyPI) is used as long as no wheels are provided.

However, using the git repository directly as in https://github.com/python-poetry/poetry/issues/7783#issuecomment-1501958487 will probably not work cross-platform (`poetry lock` on platform 1 and `poetry install` on platform 2) because in this case (IIRC) a platform specific wheel (with dependencies without markers?) is built from the git repo and its dependencies are expected to be environment independent. Thus, it will only work on the platform the lock file has been created but might not work on other platforms.

Maybe, that's a limitation, one can live with since most users prefer a package index over git dependencies.

**Comment by kayhayen** [comment]
So, I removed `requires.txt` which had no bad effect on newer pip at least, the file seems unused for pip install.

```
>>> pkginfo.SDist("dist/Nuitka-1.6rc0.tar.gz").requires
()
>>> pkginfo.SDist("dist/Nuitka-1.6rc0.tar.gz").requires_dist
()
```

From the looks of that code, that should make peotry happy, but not know about the platform specific dependencies. It sounds like poetry doesn't like that anyway. My main issue is that I do not know what else is actually using `requires.txt` and maybe old pip is in fact using that. But I believe for pip in all versions, this file is ignored, and it's only a metadata being recorded from during the runtime of the sdist creation, in which case it's probably fine if that is empty.

**Comment by magedhelmy1** [comment]
I am not sure if this is the right issue to report here or I should create a new issue - so please guide me if this is incorrect:

Can I add nutika with poetry? thank you

```
poetry add nutika
Could not find a matching version of package nutika
```

**Comment by kayhayen** [comment]
Like I said, nobody is going to be hurt, if these requirements are empty and that should be fine for now. Them being wrong is more harmful. That said, I am going to go with `Requires-Dist` once I can convince myself of it. Deleting the `requires.txt` is only a workaround for now.

**Comment by kaluluosi** [comment]
Well, I use `poetry add nuitka==1.5.3` is just fine on python3.11 .
But `poetry add nuitka` is failed with orderedset (2.0.3) build error.

**Comment by mohammed-workfellow** [comment]
Based on this thread, I used:
```
poetry shell
pip install nuitka
Collecting nuitka
  Downloading Nuitka-1.5.6.tar.gz (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 151.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting zstandard>=0.15
  Downloading zstandard-0.21.0-cp310-cp310-win_amd64.whl (511 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.3/511.3 kB 145.7 kB/s eta 0:00:00
Collecting ordered-set>=4.1.0
  Downloading ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Building wheels for collected packages: nuitka
  Building wheel for nuitka (pyproject.toml) ... done
  Created wheel for nuitka: filename=Nuitka-1.5.6-cp310-cp310-win_amd64.whl size=2874116 sha256=48b25f2b6fff3fc22e58be32ba10be25f0e63aaa84593c8aa78881f5f658c865
  Stored in directory: c:\users\mohammedsalman\appdata\local\pip\cache\wheels\03\58\fd\48650465d17747dd7daa983080b80186d50c3a26c9f0ef0196   
Successfully built nuitka
Installing collected packages: zstandard, ordered-set, nuitka
Successfully installed nuitka-1.5.6 ordered-set-4.1.0 zstandard-0.21.0
```

Strange enough, ordered set was installed just fine.

**Comment by mohammed-workfellow** [comment]
Based on this thread, I used:
```
poetry shell
pip install nuitka
Collecting nuitka
  Downloading Nuitka-1.5.6.tar.gz (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 151.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting zstandard>=0.15
  Downloading zstandard-0.21.0-cp310-cp310-win_amd64.whl (511 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.3/511.3 kB 145.7 kB/s eta 0:00:00
Collecting ordered-set>=4.1.0
  Downloading ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Building wheels for collected packages: nuitka
  Building wheel for nuitka (pyproject.toml) ... done
  Created wheel for nuitka: filename=Nuitka-1.5.6-cp310-cp310-win_amd64.whl size=2874116 sha256=48b25f2b6fff3fc22e58be32ba10be25f0e63aaa84593c8aa78881f5f658c865
  Stored in directory: c:\users\mohammedsalman\appdata\local\pip\cache\wheels\03\58\fd\48650465d17747dd7daa983080b80186d50c3a26c9f0ef0196   
Successfully built nuitka
Installing collected packages: zstandard, ordered-set, nuitka
Successfully installed nuitka-1.5.6 ordered-set-4.1.0 zstandard-0.21.0
```

Strange enough, ordered set was installed just fine.

**Comment by kayhayen** [comment]
@mohammed-workfellow pip is known to work, I think by default poetry does its own thing, and then of course has assumptions that pip doesn't do

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.7 that I just made. It's going to hit commercial tomorrow probably.
