### ISSUE TITLE
[Regression] pypdfium2 crashes Nuitka 4.0 in standalone mode

### ISSUE THREAD

**Issue by timminator** [Nuitka/Nuitka#3752]
# Bug Report

## 🐛 Bug Description

In Nuitka 4.0 pypdfium2 crashes Nuitka when compiling in standalone mode.

### 1. Nuitka Version, Python Version, OS, and Platform

```sh
4.0
Commercial: None
Python: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
Flavor: CPython Official
Executable: ~\Desktop\New folder (6)\venv-3.12\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: cl (cl 14.3).
```

### 2. How Nuitka and Python were Installed

Via pip in a venv.

### 3. Relevant PyPI Packages and Versions

The crash also occurs on older pypdfium versions so this is not related to the newest release of pypdfium2.

```sh
Package     Version Location                                                        Installer
----------- ------- --------------------------------------------------------------- ---------
Nuitka      4.0     C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages pip
ordered-set 4.1.0   C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages pip
pip         24.3.1  C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages pip
pypdfium2   5.3.0   C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages pip
zstandard   0.25.0  C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages pip
```

```sh
Nuitka 4.0 pip
ordered-set 4.1.0 pip
pip 24.3.1 pip
pypdfium2 5.3.0 pip
zstandard 0.25.0 pip
```

### 2. Short, Self-Contained, Correct, Eligible (SSCCE) Example

```python
import pypdfium2_raw.bindings as bindings

def main():
    print("pypdfium2_raw bindings loaded successfully")

if __name__ == "__main__":
    main()
```

## 📉 Expected Behavior

It should compile without any errors.

## 📄 Actual Behavior & Output

It errors out with:
```
Problem with statement at C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\pypdfium2_raw\bindings.py:41:
->     lpath = ctypes.util.find_library(name) if search_sys else None

Problem with statement at C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\pypdfium2_raw\bindings.py:25:
-> def _get_library(name, dllclass, libpaths, search_sys):

Problem with statement at C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\pypdfium2_raw\bindings.py:25:
-> def _get_library(name, dllclass, libpaths, search_sys):

Nuitka: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'C:\\Users\\Tim\\Desktop\\New
Nuitka: folder (6)\\venv-3.12\\Lib\\site-packages\\pypdfium2_raw\\bindings.py', 'module_name': <ModuleName
Nuitka: 'pypdfium2_raw.bindings'>, 'code_flags': ''}>'.
PASS 1:  33.3%|████████▎                | 1/3 modules - pypdfium2_raw.bindingsTraceback (most recent call last):
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\__main__.py", line 235, in <module>
    main()
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\__main__.py", line 217, in main
    nuitka_main()
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\MainControl.py", line 1344, in main
    _main()
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\MainControl.py", line 1168, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\MainControl.py", line 334, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\Optimization.py", line 382, in optimizeModules
    _optimizeModules(output_filename)
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\Optimization.py", line 358, in _optimizeModules
    finished = makeOptimizationPass()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\Optimization.py", line 317, in makeOptimizationPass
    changed, micro_passes = optimizeModule(current_module)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\Optimization.py", line 190, in optimizeModule
    return optimizeCompiledPythonModule(module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\Optimization.py", line 95, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\ModuleNodes.py", line 582, in computeModule
    result = module_body.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 137, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\FrameNodes.py", line 186, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 635, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\VariableAssignNodes.py", line 321, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 621, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 5402, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 621, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\FunctionNodes.py", line 1177, in computeExpressionRaw
    trace_collection.onUsedFunction(self.getFunctionBody())
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 263, in onUsedFunction
    function_body.computeFunctionRaw(self)
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\FunctionNodes.py", line 501, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\FunctionNodes.py", line 517, in computeFunction
    result = statements_sequence.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 139, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 635, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\TryNodes.py", line 65, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\StatementNodes.py", line 137, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\FrameNodes.py", line 186, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 635, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\VariableAssignNodes.py", line 321, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 621, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 125, in computeExpressionRaw
    yes_branch = branch_yes_collection.onExpression(yes_branch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 621, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 4255, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 621, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\ExpressionBasesGenerated.py", line 1189, in computeExpressionRaw
    expression = trace_collection.onExpression(self.subnode_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 621, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\ExpressionBasesGenerated.py", line 1189, in computeExpressionRaw
    expression = trace_collection.onExpression(self.subnode_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\TraceCollections.py", line 621, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\nodes\VariableRefNodes.py", line 436, in computeExpressionRaw
    very_trusted_node = self.variable_trace.getAttributeNodeVeryTrusted()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tim\Desktop\New folder (6)\venv-3.12\Lib\site-packages\nuitka\optimizations\ValueTraces.py", line 767, in getAttributeNodeVeryTrusted
    if self.assign_node.hasVeryTrustedValue():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StatementExpressionOnly' object has no attribute 'hasVeryTrustedValue'
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug
Nuitka-Reports: report.
```

## ↩️ Regression (if applicable)

This is a regression. This works fine in Nuitka 2.8.10.

[nuitka-crash-report.xml](https://github.com/user-attachments/files/25161407/nuitka-crash-report.xml)

**Comment by kayhayen** [comment]
This was a strange one, turns out importing a hard import 3 times, reveals that Nuitka is checking outdated information when removing them, going to the previous collection state instead of the current one.

This is part of the 4.0.1 hotfix I just made.
