### ISSUE TITLE
dash debug / AttributeError: type object 'nuitka_module_loader' has no attribute 'filename'

### ISSUE THREAD

**Issue by Ivorforce** [Nuitka/Nuitka#2953]
When running nuitka against the default dash example in debug mode, it fails:
```
❯ main.bin
Traceback (most recent call last):
  File "/private/var/folders/hz/m7z40m4x72d08f_7q265dn080000gn/T/onefile_96050_1719344988_118512/main.py", line 26, in <module>
  File "/private/var/folders/hz/m7z40m4x72d08f_7q265dn080000gn/T/onefile_96050_1719344988_118512/dash/dash.py", line 2099, in run
  File "/private/var/folders/hz/m7z40m4x72d08f_7q265dn080000gn/T/onefile_96050_1719344988_118512/dash/dash.py", line 1835, in enable_dev_tools
AttributeError: type object 'nuitka_module_loader' has no attribute 'filename'
```

This failure was originally reported in #1946 - which was closed due to inactivity. Just to be clear - when `debug=False` in `app.run(debug=False)`, it compiles and launches successfully.
I've created a minimal failure case with this repo: https://github.com/Ivorforce/nuitka-dash-failcase

I'm using poetry with a pyenv-managed python version - yes, I was surprised this works, too.

## Versions

```
❯ poetry run python -m nuitka --version
2.3.9
Commercial: None
Python: 3.9.17 (main, Jun 20 2023, 17:20:08)
Flavor: Homebrew Python
Executable: /Users/lukas/Library/Caches/pypoetry/virtualenvs/ecg-viewer-ZneG1Rn7-py3.9/bin/python
OS: Darwin
Arch: x86_64
macOSRelease: 14.5
Version C compiler: /usr/bin/clang (clang 15.0.0).
```

```
❯ poetry run python -m pip list -v
Package              Version
-------------------- -----------
blinker              1.8.2
certifi              2024.6.2
charset-normalizer   3.3.2
click                8.1.7
dash                 2.17.1
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
Flask                3.0.3
idna                 3.7
importlib_metadata   7.2.1
itsdangerous         2.2.0
Jinja2               3.1.4
MarkupSafe           2.1.5
nest-asyncio         1.6.0
Nuitka               2.3.9
numpy                2.0.0
ordered-set          4.1.0
packaging            24.1
pandas               2.2.2
pip                  23.3.1
plotly               5.22.0
python-dateutil      2.9.0.post0
pytz                 2024.1
requests             2.32.3
retrying             1.3.4
setuptools           70.1.1
six                  1.16.0
tenacity             8.4.2
typing_extensions    4.12.2
tzdata               2024.1
urllib3              2.2.2
Werkzeug             3.0.3
zipp                 3.19.2
zstandard            0.22.0
```

**Comment by kayhayen** [comment]
It sounds as if `enable_dev_tools` is not very desirable for deployments, but the `filename` attribute lookup is probably something that makes Nuitka's module loader incompatible and that's never a good thing.

**Comment by kayhayen** [comment]
The code in question does this, which I totally fail to understand:

```
            component_packages_dist = [
                dash_test_path
                if isinstance(package, ModuleSpec)
                else os.path.dirname(package.path)
                if hasattr(package, "path")
                else os.path.dirname(
                    package._path[0]  # pylint: disable=protected-access
                )
                if hasattr(package, "_path")
                else package.filename
                for package in packages
            ]
```

I will need to dump what `packages` is there, a Nuitka loader doesn't belong in there probably.

**Comment by kayhayen** [comment]
It's actually a `_frozen_importlib_external.SourceFileLoader` object and this code apparently expects to find a directory from them, to know where they live. Of course, this is going to be disappointing to `dash` anyway, since compiled code won't have a file in there, but I am not sure how it's used.

But either `path` or `_path` or `filename` are expected from loaders, of which Nuitka apparently exposes none, which considering that in Python land, any private attribute somebody finds is considered the best interface to use, is probably something worth adding.

**Comment by kayhayen** [comment]
So, checking out the `dir` of said source loader objects, this code is already incompatible and we need not look at dash anymore.

```
import lxml
print(lxml.__loader__.name)
print(lxml.__loader__.path)
```

**Comment by kayhayen** [comment]
First problem is of course, the loader is an object these days, and Nuitka puts the type there only, not sure why we got away with that, and which version had that last, or if it was always a mistake of mine. I know methods were added only later and normally loaders are put into sys.meta_path or queried for a registry, and there they are created, so maybe it was always wrong. But at least now it's easy to change.

**Comment by kayhayen** [comment]
```
<class 'nuitka_module_loader'>
Traceback (most recent call last):
  File "/Users/hayen/repos/Py2C/Mini.dist/Mini.py", line 3, in <module>
AttributeError: 'nuitka_module_loader' object has no attribute 'name'
```

**Comment by kayhayen** [comment]
So, Python 3.4 seems to have it had that way already, so it's fair to say this was always an incompatibility, and applies to all of Python3, crazy that nothing ever noticed that. I think loader usage in 3.4 was a lot lighter though, and the type is considered good enough in some places, but I might be confused.

**Comment by Ivorforce** [comment]
I'm happy to hear something good may come of this innocuous bug report =)
Let me know if I can help with anything.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
Since there is a bit of a risk with changing `__loader__` after having been that way for so long, I am not making this a hotfix. Generally I think people asked for spec values, and check from where things are to be loaded. The `__loader__` exists after the module is loaded, and then `__file__` and `__spec__` would still be more common uses. The code I quoted is using private attributes of loaders, no less than 3 different ones, probably to accommodate that there is source, extension and bytecode loaders, with all different internal variables.

So the code in question is particularly bad and rare, but what gives, ought to work now. Let me know if your example works, I didn't retry once I isolated things. If it then crashes on something related to not finding the source, we will have to add more stuff I guess.

**Comment by Ivorforce** [comment]
I've tested nuitka on the `release` branch. It now compiles properly, but there's a new error on execution:

```
❯ ./main.bin
Traceback (most recent call last):
  File "/private/var/folders/hz/m7z40m4x72d08f_7q265dn080000gn/T/onefile_19099_1719423482_993602/main.py", line 26, in <module>
  File "/private/var/folders/hz/m7z40m4x72d08f_7q265dn080000gn/T/onefile_19099_1719423482_993602/dash/dash.py", line 2099, in run
  File "/private/var/folders/hz/m7z40m4x72d08f_7q265dn080000gn/T/onefile_19099_1719423482_993602/dash/dash.py", line 1835, in enable_dev_tools
  File "posixpath.py", line 152, in dirname
TypeError: expected str, bytes or os.PathLike object, not getset_descriptor
```

```
❯ poetry run python -m nuitka --version
The currently activated Python version 3.10.2 is not supported by the project (~3.9).
Trying to find and use a compatible version.
Using python3.9 (3.9.17)
2.4rc7
Commercial: None
Python: 3.9.17 (main, Jun 20 2023, 17:20:08)
Flavor: Homebrew Python
Executable: /Users/lukas/Library/Caches/pypoetry/virtualenvs/ecg-viewer-qQzgjgca-py3.9/bin/python
OS: Darwin
Arch: x86_64
macOSRelease: 14.5
Version C compiler: /usr/bin/clang (clang 15.0.0).
```

**Comment by kayhayen** [comment]
That's not right, let me check, getset_descriptor is what I added, however, I think that would only happen if used on a type, but I am thinking I have objects there now, but maybe not. Thankfully you have this excellent reproducer.

**Comment by kayhayen** [comment]
I believe this would have to be the usage of `pkgutil.find_loader` which gets the spec, and then the loader from it, and we may not have an loader object there, but merely the loader type, which sort of would be another way of getting at a loader than the module attribute which I checked only.

**Comment by kayhayen** [comment]
So, this is touching on the import logic, the loaders need configuration items, that are not always available, e.g. when loading extension modules in accelerated mode. I think I will need to create the loader earlier, if any, and then pass it down the import chain for it to be attached to the spec, or maybe the spec needs to be created earlier, not sure now, but it appears a bit more invasive, but surely doable.

**Comment by kayhayen** [comment]
This is too complex for the timeline of 2.4 which is closing now.

**Comment by Ivorforce** [comment]
Ok. There's no rush because I do not need to compile dash in debug mode. Feel free to proceed in whatever way you prefer.
