### ISSUE TITLE
Dill-compat plugin is not working (even for Hello World) - "MAKE_CODEOBJECT" requires 10 arguments, but only 9 given in C compile

### ISSUE THREAD

**Issue by llamabeast1** [Nuitka/Nuitka#2152]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

1.5.5
Commercial: None
Python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\alexw\anaconda3\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).

I've also tested with 1.6rc6 (and with Python 3.11) to no avail.

* How did you install Nuitka and Python

pip (on Windows)

* The specific PyPI names and versions

Pillow==9.2.0

----

I have an issue which I've managed to make reproducible with very little code indeed!

This code:

`print("Hello world")`

Fails when I run nuitka like this:

`python -m nuitka nuitkaTest.py --enable-plugin=dill-compat`

Specifically I get this error:

```
module.__main__.c: In function '_create_compiled_function':
module.__main__.c:231:5: error: macro "MAKE_CODE_OBJECT" requires 10 arguments, but only 9 given
  231 |     );
      |     ^
module.__main__.c:221:33: error: 'MAKE_CODE_OBJECT' undeclared (first use in this function); did you mean 'CHECK_CODE_OBJECT'?
  221 |     PyCodeObject *code_object = MAKE_CODE_OBJECT(
      |                                 ^~~~~~~~~~~~~~~~
      |                                 CHECK_CODE_OBJECT
```

The dill-compat plugin seems to be causing the issue.

I note that an issue like this was raised back in 2021 (https://github.com/Nuitka/Nuitka/issues/952) , and the issue was noted as being due to an issue in dill-compat which was subsequently fixed.

In fact for the 2021 issue, only 8 out of 9 arguments were given, and now only 9 out of 10 arguments are given, so presumably another argument has been added again?

**Comment by kayhayen** [comment]
Yes, you are correct. Probably older Python versions will still work. Now 3.9 is not absurdly new, so it must have been a long time indeed. This one is neglected apparently.

**Comment by llamabeast1** [comment]
Thanks for the quick response!

I've just tested with older versions of Python going all the way back to 3.5, and get the same issue. So I wonder if it is not a Python version issue.

**Comment by llamabeast1** [comment]
In the spirit of "trying old things" I thought I'd try an old version of Nuitka, so I went back to v0.6.19.7, which was released just after the previous fix to this issue.

I can confirm that this works (test with Python 3.9).

**Comment by llamabeast1** [comment]
I narrowed it down further - dill-compat works in Nuitka 1.2.7 but not in 1.3, so it broke in December.

Surprising that it hasn't been reported before, dill seems like a very useful module to me.

**Comment by kayhayen** [comment]
Yes, it was a refactoring for how code objects are created to get a common signature. I changed it, and would like you to try it.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
btw, if you had a nice self-contained example that needs no GUI for "Nuitka-Watch", I would love to add coverage for it in the future there. There we would monitor dill PyPI upgrades and Nuitka upgrades and get alarms. That would be a valuable contribution apparently.

**Comment by llamabeast1** [comment]
Hi, I can confirm that that fix seems to have done the job. Thanks so much for getting to it so fast!

Out of interest, how long does it typically take for something to get from factory to the main branch?

I am currently on holiday but would be happy to try to write a quick test when I return. Might you be able to point me to an arbitary example of what a test might look like?

**Comment by kayhayen** [comment]
Just something that imports it, exercises some core function, and does an output that is reproducible, ideally without using the web, maybe a local image at max. 

Factory gets distributed to main and develop when I think the time has come to make a new hotfix. I do one usually roughly a week, and then stop. This one is going to a hotfix one I stabilize the onefile changes I made, probaly later this week.

I feel like, this might be relevant enough to add it to the page now.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.6 that I just made.
