### ISSUE TITLE
Compilation with '--lto' fails with "In function `loadConstantsBlob': undefined reference to `constant_bin_data'"

### ISSUE THREAD

**Issue by nixargh** [Nuitka/Nuitka#959]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
```
0.6.11.2
Python: 3.6.9 (default, Oct  8 2020, 12:12:24) 
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
```

* How did you install Nuitka and Python
pip

* Many times when you get an error from Nuitka, your setup may be special
Every time.

* Note if this is a regression
Starting to get error after upgrade from Nuitka version 0.6.9.4.

* Issue itself
I have a project with with wide dependencies that was building for about half a year but broke after version upgrade.
I want to add that on Ubuntu 20.04 it's still working, so I don't know whether it is Python or libc version matters.

Doesn't work with optmization:
`nuitka3 --standalone --plugin-enable=pylint-warnings --follow-imports --lto --output-dir=./build ./bootstrap.py`
the error is:
```
Nuitka-Options:INFO: Recursing all is the default for standalone mode and need not be specified.
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
/tmp/ccT7dRnO.ltrans30.ltrans.o: In function `loadConstantsBlob':
<artificial>:(.text+0x24512): undefined reference to `constant_bin_data'
<artificial>:(.text+0x24519): undefined reference to `constant_bin_data'
<artificial>:(.text+0x245da): undefined reference to `constant_bin_data'
collect2: error: ld returned 1 exit status
Nuitka-Scons:INFO: Running gcc -o .../build/bootstrap.dist/bootstrap -flto=8 -O3 -fpartial-inlining -freorder-functions -z noexecstack -s -Wl,-R,'$ORIGIN' -Wl,--disable-new-dtags @"./@link_input.txt -L/usr/lib -ldl -lm -lpython3.6m took 98.56 seconds
```
Works w/o _--lto_:
`nuitka3 --standalone --plugin-enable=pylint-warnings --follow-imports -output-dir=./build ./bootstrap.py`

**Comment by kayhayen** [comment]
You failed to say what it doesn't work with, you only said it's working with Ubuntu 20.04

**Comment by kayhayen** [comment]
Closing for lack of feedback.

**Comment by nixargh** [comment]
Sorry, haven't seen your question. It failed on Ubuntu 18.04.

**Comment by kayhayen** [comment]
It's with an old Nuitka, I think this was solved for 0.6.12 at some point.

**Comment by Tremeschin** [comment]
Hey, sorta inactive thread _(and didn't find the duplicate one?)_ but I'm having this issue with current `Nuitka 0.6.16.2` on Python 3.9.6 in Arch Linux OS (rolling) clean venv as well.

Steps to reproduce:

- `python -m venv temp`
- `source ./temp/bin/activate`
- `python -m pip install --upgrade pip wheel`
- `python -m pip install nuitka scons`

Create a `main.py` file as simple as a `print("Hello World")`:

- `echo "print('Hello World')" > main.py`
- `python -m nuitka --lto main.py`

Doesn't make any difference adding `--standalone` or `--onefile --linux-onefile-icon "./dummy-icon.png"`, as soon as I put the `lto` compilation fails (on one of the last steps?) with:

```bash
Backend C:  92%| .....progress bar...... | 11/12
/usr/bin/ld: /tmp/ccq1S9ml.ltrans1.ltrans.o: in function `loadConstantsBlob':
<artificial>:(.text+0xa9f3): undefined reference to `constant_bin_data'
collect2: error: ld returned 1 exit status
scons: *** [/home/tremeschin/temp/nuitka/main.bin] Error 1
```

**Comment by kayhayen** [comment]
I wonder what this `artificial` is about. Never seen that before. Maybe some hardening options are used that prevent it.

**Comment by kayhayen** [comment]
I have reproduced this myself just now, Ubuntu 16.04.7 LTS. Not happening on Debian Buster. On factory I have fixes for linker as the resource mode. Seems too old gcc and LTO is somehow buggy.

On that branch, an `NUITKA_RESOURCE_MODE=linker` environment variable exported will use the older code where it's put in there with the linker from input file. Naturally that's not working too well either, but for Linux on typical platforms it used to be good with LTO.

**Comment by kayhayen** [comment]
I am not sure, if some OS test, or gcc test should trigger to enable this automatically. What gcc version is this on your OS @nixargh 

Also, make sure to use `--static-libpython=yes` which I made to work with Debian style Python installations. It gave an even higher speedup for me, where LTO is only small.

**Comment by kayhayen** [comment]
https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
So, Buster has gcc 8, and that Ubuntu has gcc 7, and the LTS I am working with, even gcc 5. I made it so, that the environment variable is no longer needed, with gcc and not clang, but LTO on non-Windows, it will enable the linker mode as a default now, that should fixup older OSes and the default Python for LTO with Nuitka.

**Comment by kayhayen** [comment]
This is esp. important to have it fixed, because we want LTO to become the default on Linux and alike as well.

**Comment by kayhayen** [comment]
I have since had the issue with gcc 8 on Buster as well. I am making linker resource mode the default with LTO.

**Comment by Tremeschin** [comment]
Just installed from `factory` branch and `NUITKA_RESOURCE_MODE=linker` does work with `--lto` on gcc 11.1, tho on current pypi pip-installed package it fails as expected before the fixes.

**Comment by kayhayen** [comment]
This is part of the 0.6.17 release.

**Comment by kayhayen** [comment]
Please do not hijack issues, and fill out the issue template and make a new issue @wrchen-voxel
