### ISSUE TITLE
Issue trying to compile Detectron2

### ISSUE THREAD

**Issue by YacobBY** [Nuitka/Nuitka#1160]
* Issue:

I am trying to compile code using the Detectron2 library which is built upon Pytorch but can't get it to run after compilation

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

0.6.16.2
Python: 3.9.5 (default, May 19 2021, 11:32:47) 
OS: Linux
Arch: x86_64

* How did you install Nuitka and Python

Both through pip and building the latest dev version with the same results

* The specific PyPI names and versions
torch 1.9 and the latest version of Detectron2:

pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install 'git+https://github.com/facebookresearch/detectron2.git'
pip install opencv-python nuitka 

* How many times when you get an error from Nuitka, your setup may be special

Every time I try to compile a project using Detectron2 I get an error

* Demo

I have taken the Detectron2 base tutorial and left only the instance segmentation fault which produced the same error as my other project.

[I have uploaded all the files for the project here](https://tebulo-my.sharepoint.com/:f:/p/yacob_ben_youb/EpQ08IJaoq1Etp7t8KJng3cB87JX-juL0WpBTs78RIG_iQ?e=oIAiYZ) the .build and .dist folders are included for reference but are rather large so maybe you don't want to download them.

Compilation options used (used some unecessary plugins just to see if more pluginis would work, tested without as well)

  `python -m nuitka --show-progress  --show-scons  --standalone  \
    --plugin-enable=anti-bloat --plugin-enable=data-files --plugin-enable=pmw-freezer --plugin-enable=numpy \   
    --plugin-enable=torch --plugin-enable=pyzmq  \
    --assume-yes-for-downloads   \
    --follow-imports \
     Main.py
`
results in: 

```
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/.mount_ProducU3Fkou/detectron2/utils/visualizer.py", line 16, in <module detectron2.utils.visualizer>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/.mount_ProducU3Fkou/detectron2/data/__init__.py", line 4, in <module detectron2.data>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/.mount_ProducU3Fkou/detectron2/data/build.py", line 12, in <module detectron2.data.build>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/.mount_ProducU3Fkou/detectron2/structures/__init__.py", line 7, in <module detectron2.structures>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/.mount_ProducU3Fkou/detectron2/structures/masks.py", line 10, in <module detectron2.structures.masks>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/.mount_ProducU3Fkou/detectron2/layers/__init__.py", line 2, in <module detectron2.layers>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/.mount_ProducU3Fkou/detectron2/layers/batch_norm.py", line 4, in <module detectron2.layers.batch_norm>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/.mount_ProducU3Fkou/fvcore/nn/__init__.py", line 4, in <module fvcore.nn>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/.mount_ProducU3Fkou/fvcore/nn/focal_loss.py", line 50, in <module fvcore.nn.focal_loss>
  File "/tmp/.mount_ProducU3Fkou/torch/jit/_script.py", line 986, in script
  File "/tmp/.mount_ProducU3Fkou/torch/jit/frontend.py", line 240, in get_jit_def
  File "/tmp/.mount_ProducU3Fkou/torch/_utils_internal.py", line 62, in get_source_lines_and_file
OSError: Can't get source for <compiled_function sigmoid_focal_loss at 0x7f44856a6e50>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.
```

I figured that it needed to be able to read the original source files so I included thos using the include-package and include-package-data with the following command:

```
python -m nuitka --show-progress  --show-scons  --standalone  \
    --plugin-enable=anti-bloat --plugin-enable=pkg-resources --plugin-enable=implicit-imports \
    --assume-yes-for-downloads --plugin-enable=data-files --plugin-enable=pmw-freezer --plugin-enable=numpy \
    --plugin-enable=pyzmq \
    --plugin-enable=torch \
    --follow-imports \
    --include-package=detectron2 --include-package-data=detectron2 \
    --include-package-data=torch --include-package=torch  \
     Main.py
```

However this results in:
```

  File "/home/pc/Documents/nuitka_detectron2/Main.dist/Main.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/pc/Documents/nuitka_detectron2/Main.dist/torch/__init__.py", line 705, in <module torch>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/pc/Documents/nuitka_detectron2/Main.dist/torch/utils/data/__init__.py", line 4, in <module torch.utils.data>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/pc/Documents/nuitka_detectron2/Main.dist/torch/utils/data/dataset.py", line 266, in <module torch.utils.data.dataset>
  File "/home/pc/Documents/nuitka_detectron2/Main.dist/torch/utils/data/_typing.py", line 273, in __new__
  File "abc.py", line 85, in __new__
TypeError: _dp_init_subclass() missing 1 required positional argument: 'sub_cls'

```
I included a few additional plugins just to test, however without those with the following command it results in the same error: as above:
```

python -m nuitka --show-progress  --show-scons  --standalone  \
    --assume-yes-for-downloads --plugin-enable=data-files --plugin-enable=numpy \
    --plugin-enable=torch \
    --follow-imports \
    --include-package=detectron2 --include-package-data=detectron2 \
    --include-package-data=torch --include-package=torch  \
     Main.py

```
If I any additional info is needed I would be happy to provide it.

Kind regards,
Yacob

**Comment by Josh596** [comment]
@YacobBY I just got this error also, have you found a work-around?

**Comment by feiyuhuahuo** [comment]
I tried to compile myself project and encountered the same error.

**Comment by kayhayen** [comment]
Latest Torch is supposed to work with the plugin activated on 0.8.1
