### ISSUE TITLE
Error when compiling a Gtk app (gi) with Nuitka 1.1.6 on Windows

### ISSUE THREAD

**Issue by flozz** [Nuitka/Nuitka#1851]
Hello,

I had an issue compiling a GTK application on Windows with the latest Nuitka version. It used to work with Nuitka 0.6.13 and an older GTK3 version¹ but I am trying to upgrade the stack (GTK3 version, Nuitka,...).

I use gvsbuild 2022.04.1 to build GTK3. Nuitka (and Python / OS /...) versions are:

```
$ python -m nuitka --version
1.1.6
Commercial: None
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\vm0\Desktop\yoga-image-optimizer\build\__env__\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

I installed Python using the official installer form python.org and Nuitka was installed in a virtualenv using pip: `pip install nuitka==1.1.6`

Here is the list of all dependencies I have in the venv dedicated to the build:

```
$ python -m pip freeze
argcomplete==1.12.3
cffi==1.15.1
colorama==0.4.5
colorlog==4.8.0
distlib==0.3.6
filelock==3.8.0
imagequant==1.0.3
mozjpeg-lossless-optimization==1.1.1
nox==2020.12.31
Nuitka==1.1.6
Pillow==9.2.0
platformdirs==2.5.2
py==1.11.0
pycairo==1.21.0
pycparser==2.21
PyGObject==3.42.2
pyguetzli==1.0.11
Unidecode==1.3.6
virtualenv==20.16.5
yoga==1.2.1
yoga-image-optimizer @ file:///C:/Users/vm0/Desktop/yoga-image-optimizer
zopflipy==1.7
```

Here is the output of the build:

```
Nuitka-Options:INFO: Used command line options: --follow-imports --assume-yes-for-downloads --include-package=PIL --include-package-data=yoga_image_optimizer --plugin-enable=multiprocessing --plugin-enable=gi --windows-disable-console --windows-icon-from-ico=winbuild\icon.ico --standalone winbuild\yoga-image-optimizer.py
Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'orderedset' PyPI package for best Python
Nuitka:WARNING: compile time performance.
Nuitka-Plugins:WARNING: gi: Plugin is defined as always enabled.
Nuitka-Plugins:WARNING: multiprocessing: Plugin is defined as always enabled.
Nuitka:INFO: Starting Python compilation with Nuitka '1.1.6' on Python '3.9' commercial grade 'not installed'.
Nuitka-Plugins:INFO: gi: Injecting pre-module load code for module 'gi':
Nuitka-Plugins:INFO: gi:     Set typelib search path
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Traceback (most recent call last):
  File "C:\Users\vm0\Desktop\yoga-image-optimizer\build\__env__\lib\site-packages\nuitka\__main__.py", line 138, in <module>
    main()
  File "C:\Users\vm0\Desktop\yoga-image-optimizer\build\__env__\lib\site-packages\nuitka\__main__.py", line 124, in main
    MainControl.main()
  File "C:\Users\vm0\Desktop\yoga-image-optimizer\build\__env__\lib\site-packages\nuitka\MainControl.py", line 928, in main
    addIncludedDataFilesFromPackageOptions()
  File "C:\Users\vm0\Desktop\yoga-image-optimizer\build\__env__\lib\site-packages\nuitka\freezer\IncludedDataFiles.py", line 327, in addIncludedDataFilesFromPackageOptions
    for included_datafile in Plugins.considerDataFiles(module=module):
  File "C:\Users\vm0\Desktop\yoga-image-optimizer\build\__env__\lib\site-packages\nuitka\plugins\Plugins.py", line 563, in considerDataFiles
    for value in plugin.considerDataFiles(module):
  File "C:\Users\vm0\Desktop\yoga-image-optimizer\build\__env__\lib\site-packages\nuitka\plugins\standard\GiPlugin.py", line 63, in considerDataFiles
    gi_repository_path = os.path.dirname(path.introspection_module)
AttributeError: 'NoneType' object has no attribute 'introspection_module'
```

---

I can reproduce the issue with the following minimal example file:

```python
from gi.repository import Gtk
```

compiled with the following options:

```
$ python -m nuitka --standalone --plugin-enable=gi example.py
```

---

¹ It used to work with Nuitka 0.6.13 without the `--plugin-enable=gi` option (I imported manually the hidden imports of gi overrides)

**Comment by kayhayen** [comment]
The plugin doesn't handle a failure to locate the typelib, however I would very much like to understand why this gives an error for you, but I think we need to ignore this kind of error, it appears, that you are not using GObject for some reason, and that is normal. I checked with MSYS2, and it's working all nicely and I cannot get it to not work with it. I intend to make this part of a next hotfix to handle this error.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by flozz** [comment]
The compilation work with the factory version. :+1: 

I still have runtime issues but this is more likely a problem with gvsbuild / Gtk itself (I still work on this) :)

**Comment by flozz** [comment]
My runtime issue is the following:

```
ImportError: cannot import name GObject, introspection typelib not found
```

it occurs despite the fact I defined the `GI_TYPELIB_PATH` in the script:

```python
ROOT = pathlib.Path(__file__).resolve().parent
os.environ["GI_TYPELIB_PATH"] = str(ROOT / "gtk" / "lib" / "girepository-1.0")
```

I can't figure why it does not find it anymore whereas it used to work...

**Comment by flozz** [comment]
I think my issue is here: https://github.com/Nuitka/Nuitka/blob/factory/nuitka/plugins/standard/GiPlugin.py#L43

this line:

```python
if not os.environ.get("GI_TYPELIB_PATH="):
```

should probably be:

```python
if not os.environ.get("GI_TYPELIB_PATH"):
```

(the `=` sign at the end of the env var name) :)

**Comment by flozz** [comment]
I compiled successfully using Nuitka 1.1.6, with the `GiPlugin.py` file from the `factory` branch, and the `=` removed from the environment variable name:

* https://github.com/flozz/Nuitka/blob/v1.1.6-patched-gi/nuitka/plugins/standard/GiPlugin.py

*Here are the complete build scripts and instructions I use for my project if it can help: https://github.com/flozz/yoga-image-optimizer/tree/update-winbuild/winbuild#readme*

Thank you very much for your help! :)

**Comment by kayhayen** [comment]
Thanks for spotting that, I will include it in 1.1.7 which should be coming shortly.

**Comment by kayhayen** [comment]
It's on factory now too.

**Comment by kayhayen** [comment]
Part of the 1.1.7 hotfix that was made a while ago, and 1.1.8 since of course.

**Comment by flozz** [comment]
Thank you very much for all your work on Nuitka! 😃
