### ISSUE TITLE
ImportError: cannot import name 'isMutable'

### ISSUE THREAD

**Issue by gvanem** [Nuitka/Nuitka#1292]
I just discovered Nuitka. But have problems building a simple `hello world` sample.
See below.

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
> python -m nuitka --version
0.6.18rc8
Commercial: None
Python: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]
Flavor: Unknown
Executable: F:\ProgramFiler\Python36\python.exe
OS: Windows
Arch: x86
```

* How did you install Nuitka and Python
```
md f:\ProgramFiler\Python36\Lib\site-packages\nuitka
cd F:\ProgramFiler\Python36\Lib\site-packages\nuitka
git clone https://github.com/Nuitka/Nuitka.git .
py -3 setup.py install
```

* Did you use pip, anaconda, deb, rpm, from source, in a virtualenv or not,
this is very important usually.

**No**

* My steps in building a stand-alone program from a `hello.py` from the `README.md`:
```py 
def talk (message):
    return "Talk " + message
def main():
    print (talk("Hello World"))
main()
```
*  using this command (in `f:\ProgramFiler\Python36\Lib\site-packages\nuitka\test`):
```
f:\ProgramFiler\Python36\Scripts\nuitka.bat --standalone --show-scons --show-progress --verbose --msvc=14.2  hello.py

Traceback (most recent call last):
  File "F:\ProgramFiler\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\ProgramFiler\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\ProgramFiler\Python36\lib\site-packages\nuitka-0.6.18rc8-py3.6.egg\nuitka\__main__.py", line 142, in <module>
    main()
  File "F:\ProgramFiler\Python36\lib\site-packages\nuitka-0.6.18rc8-py3.6.egg\nuitka\__main__.py", line 91, in main
    reExecuteNuitka(pgo_filename=None)
  File "F:\ProgramFiler\Python36\lib\site-packages\nuitka-0.6.18rc8-py3.6.egg\nuitka\utils\ReExecute.py", line 65, in reExecuteNuitka
    os.environ["NUITKA_PTH_IMPORTED"] = repr(detectPthImportedPackages())
  File "F:\ProgramFiler\Python36\lib\site-packages\nuitka-0.6.18rc8-py3.6.egg\nuitka\importing\PreloadedPackages.py", line 101, in detectPthImportedPackages
    from nuitka.nodes.ImportNodes import isHardModuleWithoutSideEffect
  File "F:\ProgramFiler\Python36\lib\site-packages\nuitka-0.6.18rc8-py3.6.egg\nuitka\nodes\ImportNodes.py", line 48, in <module>
    from nuitka.specs.BuiltinParameterSpecs import (
  File "F:\ProgramFiler\Python36\lib\site-packages\nuitka-0.6.18rc8-py3.6.egg\nuitka\specs\BuiltinParameterSpecs.py", line 27, in <module>
    from .ParameterSpecs import ParameterSpec, TooManyArguments, matchCall
  File "F:\ProgramFiler\Python36\lib\site-packages\nuitka-0.6.18rc8-py3.6.egg\nuitka\specs\ParameterSpecs.py", line 32, in <module>
    from nuitka import Variables
  File "F:\ProgramFiler\Python36\lib\site-packages\nuitka-0.6.18rc8-py3.6.egg\nuitka\Variables.py", line 29, in <module>
    from nuitka.nodes.shapes.StandardShapes import tshape_unknown
  File "F:\ProgramFiler\Python36\lib\site-packages\nuitka-0.6.18rc8-py3.6.egg\nuitka\nodes\shapes\StandardShapes.py", line 23, in <module>
    from nuitka.codegen.c_types.CTypePyObjectPtrs import CTypePyObjectPtr
  File "F:\ProgramFiler\Python36\lib\site-packages\nuitka-0.6.18rc8-py3.6.egg\nuitka\codegen\c_types\CTypePyObjectPtrs.py", line 46, in <module>
    from nuitka.Constants import isMutable
ImportError: cannot import name 'isMutable'
```

The function `isMutable()` is [here](https://github.com/Nuitka/Nuitka/blob/develop/nuitka/Constants.py#L202). So what is this all about?

**Comment by kayhayen** [comment]
Your installation method looks very much as if it could break things, with the nuitka folder in `site-packages` and a clone in there, that may be confused with the egg contents.

**Comment by kayhayen** [comment]
I tried it myself, and it works flawlessly, the only complaint I have is that it creates executables, `nuitka.exe` and so on, that do not work at all, but I just made a chance to remove them, they do not affect you however. I am assuming, that site-package/nuitka and the egg can both be used by Nuitka, and well, that's not a bug, you are just not supposed to manually place any files below `site-packages`.

**Comment by gvanem** [comment]
>  you are just not supposed to manually place any files below site-packages.

Why? It works with Python 2.7. Why not Python 3.6?

**Comment by gvanem** [comment]
I now did a complete clean-up and reinstall. This time in another directory; if that what you mean is wrong.
Steps:
```
md F:\MingW32\src\Languages\Nuitka
cd F:\MingW32\src\Languages\Nuitka
git clone https://github.com/Nuitka/Nuitka.git .
py -3 setup.py install
```

Same `hello.py` and command as above:
```
f:\ProgramFiler\Python36\Scripts\nuitka.bat --standalone --show-scons --show-progress --verbose --msvc=14.2  hello.py
```
yields the same error:
```
    from nuitka.Constants import isMutable
ImportError: cannot import name 'isMutable'
```

What's the cause for this? Anyone?

**Comment by kayhayen** [comment]
As to why this happens, in Python3, a directory is a package, even without an `__init__.py`, so immediately after you cloned Nuitka, the package "Nuitka" becomes avalable. Now of course, Nuitka uses `nuitka`, but on case insensitive platforms like Windows you are therefore immediately able to import both.

You would have to delete your Python installation, definitely the Nuitka folder in there.

**Comment by gvanem** [comment]
> You would have to delete your Python installation, 

Are you serious? 

> definitely the Nuitka folder in there.

You mean that *definitely the Nuitka folder **is** in there.*? It's not since I did the clean-up and reinstall:
`envtool --evry -Dc Nuitka` lists only the clone directory `F:\MingW32\src\Languages\Nuitka`.

I do not believe this directory becomes part of `sys.path` in any way. But just as a test, I renamed it to `Nuitka-git-clone-dir`. 
But the same problem remains.

Care to explain in some more details what you think is wrong?

**Comment by gvanem** [comment]
I tried using the MSI: `Nuitka-6.1.177.win32.py36.msi`. Now the error is different:
```
File "F:\ProgramFiler\Python36\lib\site-packages\nuitka\nodes\ConstantRefNodes.py", line 36, in <module>
    from nuitka.Constants import (
ImportError: cannot import name 'getUnhashableConstant'
```

> I think you have a folder named Nuitka in your Python installation,

Well I do have that (`F:\ProgramFiler\Python36\lib\site-packages\nuitka`). Since, duh! the MSI installer put it there.
Or should I've installed into `%APPDATA%\Python\Python36\site-packages\nuitka` instead? I've tried that with
`py -3 setup.py install --user` which gave the same import error.

I've installed a lot of Python3 packages over the years. But nothing as confusing and obfuscated as this.

**Comment by kayhayen** [comment]
I haven't verified that the MSI files work in a very long time. I just did, they work just fine. 

What I found a pity, as a note to self, is that the MSI uninstallation leaves an `nuitka` directory in site-packages, with the bytecode, MSI install and `setup.py install` are both not undoable without manual interaction. And deleting a folder is not necessarily enough to undo `install`.

Your comment about `%APPDATA%` is intriguing though, maybe there is an older version somewhere, or something like that, anyway, this is how I cleaned up my install after `install`:

```
>>> import nuitka
>>> nuitka
```
rm -rf <what_ever_it_said_

**Comment by kayhayen** [comment]
My research about `bdist_msi` bugs has revealed that it has been deprecated in 3.9 and will be removed in 3.11, so I should not worry to much about those I guess.

**Comment by gvanem** [comment]
> Your comment about %APPDATA% is intriguing though, maybe there is an older version somewhere, or something like that

No there is not. But some commands work. Like:
```
py -3 -m nuitka --follow-imports --mingw64 --verbose hello.py

...
f:/MinGW32/TDM-gcc/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: 
skipping incompatible F:\ProgramFiler\Python36\libs/python36.lib when searching for -lpython36
collect2.exe: error: ld returned 1 exit status
```
(generating x64 objects under `hello.build`), My MinGW (TDM-gcc v.10.3.0) is dual-mode with `-m64` as default. 
So I have tweak a `-m32` into it somehow I guess....

**Comment by kayhayen** [comment]
Well, you made sure you picked a supported C compiler, did you? Well of course not. TDM is not supported. See #35 which states that.

Nuitka would download a supported one if it wasn't finding one. With the next release, the gcc version check for 11.2 ought to catch this as TDM has not been updated for a while, and then it would download it.

I think Nuitka checks compiler vs. Python arch though, so I think this might not be about architecture there, but if it was, it would mean TDM very nearly works maybe, which might be interesting news. But a dual mode gcc binary would have to be a x64 binary and be detected as mismatching. Bonus points if you can point out why that's not recognized.

But I doubt TDM has the LTO correctly that we now use. For specifying linker options, set environment variable `LDFLAGS` to what you want. That way no code change is needed. The platform support needs to be really good for standalone to work well, which is mostly why other MinGW forms are rejected.
