### ISSUE TITLE
any nuitka compilation fails, inside a linux conda/mamba environment, from python version 3.11.4

### ISSUE THREAD

**Issue by bhennebel** [Nuitka/Nuitka#2521]
Nuikta compilation of a hello world python script fails with this error : 
"undefined reference to `__warn_memset_zero_len'".

This occurs only when this 3 conditions are met together : linux + mamba env + python version >= 3.11.4

A docker file is attached  to replay these tests (containing its self documentation) and to choose python version + env kind to test, compiler gcc/clang. 

Additional context:
- it was not observed on windows (and not tested on mac...)
- it occurs with nuitka version 1.8.4 (and likely previous versions which can be tested with this Dockerfile).
- it occurs when compiling with gcc (at least from version 8 to 12) and clang
- it occurs when using mamba env
- when using continuumio 's conda instead of mambafore, compilation result seems to be unstable : failing sometimes (with python 3.11.4) or passing some othertimes (but downgrading python version to 3.11.2)

The main command to run is the following, to let this compilation error appears (mamba env + python 3.11.4):
DOCKER_BUILDKIT=1 docker build --no-cache -f Dockerfile_reproducer_nuitka.txt --target mamba_env .

[Dockerfile_reproducer_nuitka.txt](https://github.com/Nuitka/Nuitka/files/13217899/Dockerfile_reproducer_nuitka.txt)

**Comment by kayhayen** [comment]
I suspect that FORIFY_SOURCE is specified somewhere. I recall that for 1.9 I made changes, because of how it affects `assert`. Generated code of Nuitka might make an empty `memset`, or this is just trying to be able to do that warning at run time. Does Scons show something about inherited options?

**Comment by bhennebel** [comment]
- After further analysis (with the help of updated and attached Dockerfile), I first must update my statement : nuitka only fails to compile when working with mamba env, and not with continuumio 's conda. Python versions impacted are still 3.11.4 and above...

- I can notice, in mamba, that libstatic-python version does not match with python version ! The libstatic-python lib always points to 3.11.6 whatever the python (3.11.4 or 3.11.5). Note so nice...But even forcing  mamba to install the right version of libstatic-python does not prevent nuitka compilation to fail with always the same error.

- So just have a "diff" look on these attached texts files to notice:
    -  the diffs between conda and mamba dependencies
    -  the diffs between different mamba compilations
    - notice the libstatic-python version error. 
    - This text files contain indeed : 
            1) the compilation stdout
            2) the env list (conda/ mamba list)
            3) the nuitka compilation report


- In short, the scons results for mamba with python 3.11.4 are the following : 
/usr/bin/ld: /usr/bin/ld: DWARF error: can't find .debug_ranges section.
/opt/conda/envs/test_env/lib/libpython3.11.a(pystrtod.o): in function `PyOS_double_to_string':
pystrtod.c:(.text.hot.PyOS_double_to_string+0x1b9): undefined reference to `__warn_memset_zero_len'
collect2: error: ld returned 1 exit status
scons: *** [/test_dir/hello_world.bin] Error 1
scons: internal stack trace:
  File "/opt/conda/envs/test_env/lib/python3.11/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Job.py", line 258, in run
    task.execute()
  File "/opt/conda/envs/test_env/lib/python3.11/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Script/Main.py", line 206, in execute
    SCons.Taskmaster.OutOfDateTask.execute(self)
  File "/opt/conda/envs/test_env/lib/python3.11/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "/opt/conda/envs/test_env/lib/python3.11/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Node/__init__.py", line 766, in build
    self.get_executor()(self, **kw)
  File "/opt/conda/envs/test_env/lib/python3.11/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 397, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/test_env/lib/python3.11/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 131, in execute_action_list
    raise status    # TODO pylint E0702: raising int not allowed
    ^^^^^^^^^^^^
scons: building terminated because of errors.


- Note: this problem has not a high priority for me, as I still can work with 3.11.3 python version and now aware of the present limitation. But, it could be more impacting for new people discovering nuitka on the increasingly popular miniforge/mambaforge environments. So no hurry for me on this subject  (and in any case I will go to the commercial version in a couple of weeks to support this nice nuitka project !)


[
[conda_python_3_11_3_PASS.txt](https://github.com/Nuitka/Nuitka/files/13230542/conda_python_3_11_3_PASS.txt)
[conda_python_3_11_4_PASS.txt](https://github.com/Nuitka/Nuitka/files/13230543/conda_python_3_11_4_PASS.txt)
[conda_python_3_11_5_PASS.txt](https://github.com/Nuitka/Nuitka/files/13230544/conda_python_3_11_5_PASS.txt)
[Dockerfile_reproducer_nuitka.txt](https://github.com/Nuitka/Nuitka/files/13230545/Dockerfile_reproducer_nuitka.txt)
[mamba_python_3_11_3_clang_compiler_PASS.txt](https://github.com/Nuitka/Nuitka/files/13230547/mamba_python_3_11_3_clang_compiler_PASS.txt)
[mamba_python_3_11_3_PASS.txt](https://github.com/Nuitka/Nuitka/files/13230548/mamba_python_3_11_3_PASS.txt)
[mamba_python_3_11_4_clang_compiler_FAIL.txt](https://github.com/Nuitka/Nuitka/files/13230549/mamba_python_3_11_4_clang_compiler_FAIL.txt)
[mamba_python_3_11_4_FAIL.txt](https://github.com/Nuitka/Nuitka/files/13230550/mamba_python_3_11_4_FAIL.txt)
[mamba_python_3_11_4_forcing_libstatic_3_11_4_FAIL.txt](https://github.com/Nuitka/Nuitka/files/13230551/mamba_python_3_11_4_forcing_libstatic_3_11_4_FAIL.txt)
[mamba_python_3_11_5_FAIL.txt](https://github.com/Nuitka/Nuitka/files/13230552/mamba_python_3_11_5_FAIL.txt)
[mamba_python_3_11_5_forcing_libstatic_3_11_5_FAIL.txt](https://github.com/Nuitka/Nuitka/files/13230553/mamba_python_3_11_5_forcing_libstatic_3_11_5_FAIL.txt)
[mamba_python_3_11_6_FAIL.txt](https://github.com/Nuitka/Nuitka/files/13230554/mamba_python_3_11_6_FAIL.txt)
](url)

**Comment by kayhayen** [comment]
There are no inherited flags, so fortify source is not really coming from environment, but maybe from clang. I am not sure, I ever provided `--clang` to Anaconda, it is supposed to find CondaCC itself, and `/usr/bin/clang` is probably a mismatch. Remove it.

**Comment by kayhayen** [comment]
it prevents wonderful options like this 

```
    # Allow CondaCC to be detected if it is in PATH.
    if isLinux():
        SCons.Tool.gcc.compilers.insert(0, "x86_64-conda-linux-gnu-gcc")

    if isMacOS() and "CONDA_TOOLCHAIN_BUILD" in os.environ:
        SCons.Tool.gcc.compilers.insert(
            0, "%s-clang" % os.environ["CONDA_TOOLCHAIN_BUILD"]
        )

```

If Anaconda Linux compiles a static link library how sure are we it's picked up by clang correctly? Not very.

I wonder if this should be less optional:

```
-  Anaconda: Use ``CondaCC`` from environment variables for Linux and
   macOS, in case it is installed. This can be done with e.g. ``conda
   install gcc_linux-64`` on Linux or ``conda install clang_osx-64`` on
   macOS.
```

With Anaconda, maybe outside of Windows, we have no reason to not use the CondaCC. On Windows it's pretty bad and not good enough for Nuitka, or did they update it?

```
    # CondaCC or newer.
    if env.mingw_mode and env.gcc_version < (5, 3):
        scons_logger.sysexit(
            """\
The MinGW64 compiler %s (version %s) doesn't have the sufficient \
version (>= 5.3)."""
            % (env.the_compiler, env.gcc_version)
        )
```

**Comment by ygl89** [comment]
The same issue with conda environment:Ubuntu 20, gcc 9, Python 3.8 and Ubuntu 22, gcc 11, Python 3.12
lib/libpython3.12.a(pystrtod.o): in function `memset':
undefined reference to `__warn_memset_zero_len'

**Comment by kayhayen** [comment]
Not using Anaconda compiler is probably an issue. We are making a bigger change, where standalone compilation with use a backend of course, which will be essentially a Miniforge with a Python patched by Nuitka, GCC, and everything necessary, so we are going to force all compilation on Linux that is not addressing the native system, but a portable binary, to go through a fixed toolchain. In the mean time, install c-compiler in your Anaconda, and on some arches, Nuitka will pick it up automatically already, in the future, Nuitka is not going to use your environment at all anymore, neither gcc, nor anything else. This is just too incompatible to suffer through, plus doing standalone Linux right with system gcc, is not necessarily happening I think.

**Comment by 67906980725** [comment]
> Can confirm the issue on Ubuntu 20, gcc 11, Python >3.9, miniconda environment. Nuitka 2.0 (installed from pip).

I also encountered this error when installing Nuitka using pip under Venv (Micromamba, and MiniConda3 using Python 3.11) for Fedora40, GCC14, . After deleting Nuitka, reinstalling Nuitka using Micromamba and MiniConda commands will solve the problem

**Comment by thelongestusernameofall** [comment]
how to make a quick fix?

**Comment by kayhayen** [comment]
Standalone Backend Python will be a 2.6 goal.

**Comment by JavierYepez** [comment]
Can confirm the issue on Debian 12, gcc 12.2.0, Python 3.11.12, mamba environment. Nuitka 2.7.5 (installed from pip).

**Comment by kayhayen** [comment]
Install c-compiler in your Anaconda, and on some arches, Nuitka will pick it up automatically already, if you have a more special one, and arm may already not be covered, just help by adding to here:

```
    # Allow CondaCC to be detected if it is in PATH.
    if isLinux():
        SCons.Tool.gcc.compilers.insert(0, "x86_64-conda-linux-gnu-gcc")
```

That should make it be picked up on that arch, but for others, the arch prefix might be missing and hard to come by, as out arch detection and condas naming, as usual will mismatch. On the other hand, I don't even know if Anaconda supports arm linux.

As for the Standalone backend, my plan to make a fork that is like a private copy of C-compiler, Python, etc. from Anaconda, and to always use that no matter what the frontend Python is, I have not really plans to use that.

That said, forcing the C compiler, to be a conda-cc like the one above, should indeed be a plan.

**Comment by kayhayen** [comment]
This would in fact be a very nice first issue for somebody willing to dive into these things and would be good to see resolved.
