### ISSUE TITLE
Python3.13: Packages of the form "x.x" failed to import when extension module package context workaround is used

### ISSUE THREAD

**Issue by Areopagitics** [Nuitka/Nuitka#3445]
Both my custom maturin module, rust_package and rpds-py (also a maturin module but from pypi) are not importing properly when using --follow-imports (--standalone, etc). It works fine on Windows.

```
    from .rpds import *
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 946, in _load_unlocked
KeyError: 'rpds.rpds'
```

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

2.6.9
Commercial: None
Python: 3.13.3 (v3.13.3:6280bb54784, Apr  8 2025, 10:47:54) [Clang 15.0.0 (clang-1500.3.9.4)]
Flavor: CPython Official
GIL: yes
Executable: ~/Desktop/Program/.venv/bin/python3.13
OS: Darwin
Arch: arm64
macOSRelease: 15.4.1
Version C compiler: /usr/bin/clang (clang 17.0.0).

- How did you install Nuitka and Python

  Python from the official website (I also tried homebrew with same problem)
  Nuitka from pip

- The specific PyPI names and versions

Package                   Version     Editable project location            Location                                                                                                               Installer
------------------------- ----------- ------------------------------------ ---------------------------------------------------------------------------------------------------------------------- ---------
attrs                     25.3.0                                           .venv/lib/python3.13/site-packages                                                pip
babel                     2.17.0                                           .venv/lib/python3.13/site-packages                                                pip
certifi                   2025.1.31                                        .venv/lib/python3.13/site-packages                                                pip
cffi                      1.17.1                                           .venv/lib/python3.13/site-packages                                                pip
charset-normalizer        3.4.1                                            .venv/lib/python3.13/site-packages                                                pip
cn2an                     0.5.23                                           .venv/lib/python3.13/site-packages                                                pip
colorama                  0.4.6                                            .venv/lib/python3.13/site-packages                                                pip
coloredlogs               15.0.1                                           .venv/lib/python3.13/site-packages                                                pip
csvw                      3.5.1                                            .venv/lib/python3.13/site-packages                                                pip
Cython                    3.0.12                                           .venv/lib/python3.13/site-packages                                                pip
dlinfo                    2.0.0                                            .venv/lib/python3.13/site-packages                                                pip
flatbuffers               25.2.10                                          .venv/lib/python3.13/site-packages                                                pip
fugashi                   1.4.0                                            .venv/lib/python3.13/site-packages                                                pip
humanfriendly             10.0                                             .venv/lib/python3.13/site-packages                                                pip
idna                      3.10                                             .venv/lib/python3.13/site-packages                                                pip
isodate                   0.7.2                                            .venv/lib/python3.13/site-packages                                                pip
jaconv                    0.4.0                                            .venv/lib/python3.13/site-packages                                                pip
jieba                     0.42.1                                           .venv/lib/python3.13/site-packages                                                pip
joblib                    1.4.2                                            .venv/lib/python3.13/site-packages                                                pip
jsonschema                4.23.0                                           .venv/lib/python3.13/site-packages                                                pip
jsonschema-specifications 2025.4.1                                         .venv/lib/python3.13/site-packages                                                pip
language-tags             1.2.0                                            .venv/lib/python3.13/site-packages                                                pip
maturin                   1.8.3                                            .venv/lib/python3.13/site-packages                                                pip
misaki                    0.7.4                                            .venv/lib/python3.13/site-packages                                                pip
mojimoji                  0.0.13                                           .venv/lib/python3.13/site-packages                                                pip
mpmath                    1.3.0                                            .venv/lib/python3.13/site-packages                                                pip
Nuitka                    2.6.9                                            .venv/lib/python3.13/site-packages                                                pip
numpy                     2.2.5                                            .venv/lib/python3.13/site-packages                                                pip
onnxruntime               1.21.1                                           .venv/lib/python3.13/site-packages                                                pip
opusenc                   1.0                                              .venv/lib/python3.13/site-packages/opusenc-1.0-py3.13-macosx-10.13-universal2.egg
opusenc                   1.0                                              .venv/lib/python3.13/site-packages/opusenc-1.0-py3.13-macosx-10.13-universal2.egg
ordered-set               4.1.0                                            .venv/lib/python3.13/site-packages                                                pip
packaging                 25.0                                             .venv/lib/python3.13/site-packages                                                pip
phonemizer-fork           3.3.2                                            .venv/lib/python3.13/site-packages                                                pip
pip                       25.0.1                                           .venv/lib/python3.13/site-packages                                                pip
proces                    0.1.7                                            .venv/lib/python3.13/site-packages                                                pip
protobuf                  6.30.2                                           .venv/lib/python3.13/site-packages                                                pip
pycparser                 2.22                                             .venv/lib/python3.13/site-packages                                                pip
pyparsing                 3.2.3                                            .venv/lib/python3.13/site-packages                                                pip
pypinyin                  0.54.0                                           .venv/lib/python3.13/site-packages                                                pip
python-dateutil           2.9.0.post0                                      .venv/lib/python3.13/site-packages                                                pip
rdflib                    7.1.4                                            .venv/lib/python3.13/site-packages                                                pip
referencing               0.36.2                                           .venv/lib/python3.13/site-packages                                                pip
regex                     2024.11.6                                        .venv/lib/python3.13/site-packages                                                pip
requests                  2.32.3                                           .venv/lib/python3.13/site-packages                                                pip
rfc3986                   1.5.0                                            .venv/lib/python3.13/site-packages                                                pip
rpds-py                   0.24.0                                           .venv/lib/python3.13/site-packages                                                pip
rust_package              0.1.0                                        .venv/lib/python3.13/site-packages                                                pip
segments                  2.3.0                                            .venv/lib/python3.13/site-packages                                                pip
setuptools                79.0.1                                           .venv/lib/python3.13/site-packages                                                pip
six                       1.17.0                                           .venv/lib/python3.13/site-packages                                                pip
sounddevice               0.5.1                                            .venv/lib/python3.13/site-packages                                                pip
sympy                     1.13.3                                           .venv/lib/python3.13/site-packages                                                pip
typing_extensions         4.13.2                                           .venv/lib/python3.13/site-packages                                                pip
unidic-lite               1.0.8                                            .venv/lib/python3.13/site-packages                                                pip
uritemplate               4.1.1                                            .venv/lib/python3.13/site-packages                                                pip
urllib3                   2.4.0                                            .venv/lib/python3.13/site-packages                                                pip
wxPython                  4.2.3                                            .venv/lib/python3.13/site-packages                                                pip
zstandard                 0.23.0                                           .venv/lib/python3.13/site-packages                                                pip

- Many times when you get an error from Nuitka, your setup may be special

nuitka MyPythonFile.py works fine but not with --follow-imports (or standalone, etc)

- Also supply a Short, Self Contained, Correct, Eligible Example

```
from rpds import HashTrieMap

m = HashTrieMap({"foo": "bar", "baz": "quux"})
```

- Provide in your issue the Nuitka options used

  nuitka --follow-imports test.py

**Comment by Areopagitics** [comment]
There was another similar issue #1844 that was closed, which referenced another maturin built module.

**Comment by Areopagitics** [comment]
It ended up working fine with python 3.12.

**Comment by kayhayen** [comment]
With Python3.13 I am currently getting this one, which I have seen another report about previously

```
Traceback (most recent call last):
  File "/Users/hayen/repos/Py2C/Mini.dist/Mini.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/Users/hayen/repos/Py2C/Mini.dist/rpds/__init__.py", line 1, in <module rpds>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
SystemError: <built-in method create_module of type object at 0x1022e5490> returned NULL without setting an exception
```

I indeed fixed the KeyError in a hotfix 2.6.6 forgot now, so according to changelog this should not happen, and it doesn't for me, at least now with develop.

```
-  **Python3.12+**: Workaround for failure to set package context for
   extension modules causing major compatibility issues previously.

   Without static libpython we don't have the ability to set the package
   context and then extension modules corrupt global namespace by
   creating a module without the package name. This can collide with
   existing package names. For ``PySide6QtAds`` package this was
   happening. Protect against that by saving and restoring old module
   value and correct the loaded module name afterwards.

   Previously, e.g. ``PySide6.QtWidgets`` was loaded as ``QtWidgets`` as
   well in ``sys.modules`` and that was corrected by the Nuitka loader
   storing it under the correct name as well, only.

   Also rename further sub-modules potentially created by extension
   modules during their load already. This should increase its coverage
   by a lot. We had manually done this for ``onnx`` and ``mediapipe`` so
   far, but e.g. ``paddleocr`` was affected too, any maybe other
   packages. Most recently new ``scipy`` added itself to that list.

   The most important platform this impacts is Windows and also macOS if
   using official CPython flavor. Fixed in 2.6.6 already.
```

The CPython on macOS is affected by the issue, your report refers to 2.6.9 though, but that shouldn't be possible. However, this might be a sign of something bad happening. My recent 3.13 fixes for dictionary that will be in 2.7 only, were also used, but maybe this is still a corruption.

I need to narrow down what our `create_module` (which for 2.7 already loads the extension module) could be getting an idea of returning NULL.

**Comment by kayhayen** [comment]
So, turns out this is a shim link library, and as such provides no value. Disabling it makes no difference, but gives a slightly larger binary, so we can ignore that side of the story. Instead I need to verify, if the 3.13 code uses the accessible symbol again unlike 3.12 did.

**Comment by kayhayen** [comment]
So, it turns out, that 3.13 code is roughly the same as 3.12, and prevents `PyModule_Create` when used by the extension module from proper working. Also the issue is the same on Windows with Python3.13 not working and 3.12 working.

I need to check if `rdps.rdps` as apparently produced by 3.13 is actually the correct module in `sys.modules` after running the extension module entry point, and if it is, we can skip the correction step I guess.

**Comment by kayhayen** [comment]
Ok, so we do this, and that is what's tripping it up.

```
#if PYTHON_VERSION >= 0x3d0
    Nuitka_SetModuleString(full_name, module);
#endif
```

Not sure now why this is done for 3.13 only, but apparently some code in the loading may no longer put the module into `sys.modules` directly, so we do it and then we better ignore it being there.

**Comment by kayhayen** [comment]
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 
	
Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment]
This is part of the stable release 2.7 that I just made.

**Comment by Areopagitics** [comment]
Thanks for fixing it so quick ... I'm getting a similar error for another package when building on MacOS 3.13 with --follow-imports again.  It works fine in python 3.12 again.

```
Traceback (most recent call last):
  File "/Users/user/Desktop/Project/Project.py", line 24, in <module>
    from misaki import zh,ja
  File "/Users/user/Desktop/Project/.venv/lib/python3.13/site-packages/misaki/ja.py", line 4, in <module misaki.ja>
    import pyopenjtalk
  File "/Users/user/Desktop/Project/.venv/lib/python3.13/site-packages/pyopenjtalk/__init__.py", line 25, in <module pyopenjtalk>
    from .htsengine import HTSEngine
ImportError: cannot import name 'HTSEngine' from 'pyopenjtalk.htsengine' (/Users/user/Desktop/Project/.venv/lib/python3.13/site-packages/pyopenjtalk/htsengine.cpython-313-darwin.so)
```
