### ISSUE TITLE
Debian/Python 3.12: compilation "hello word" program failed

### ISSUE THREAD

**Issue by antsvil** [Nuitka/Nuitka#2960]
Hi,
if I compile a simple "hello word" program I get the errors indicated below (crash report). The problem occurred after upgrading Python from version 3.11.9 to 3.12.4, on Debian/sid. I can't determine whether it depends on Debian packages or Nuitka (with the previous version of Python it worked fine).
Thank you,
Antonio
----
```
$ pipx install nuitka
$ nuitka3 --version
2.3.10
Commercial: None
Python: 3.12.4 (main, Apr 10 2024, 13:16:36) [GCC 13.2.0]
Flavor: Debian Python
Executable: /home/test/.local/pipx/venvs/nuitka/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian sid
Version C compiler: /bin/gcc (gcc 13).
```
----
```
<?xml version='1.0' encoding='utf8'?>
<nuitka-compilation-report nuitka_version="2.3.10" nuitka_commercial_version="not installed" completion="error exit message (1)" exit_message="Failed unexpectedly in Scons C backend compilation.">
  <scons_error_reports>
    <scons_error_report>
      <command>gcc -o "/home/test/test.bin" -flto=24 -fuse-linker-plugin -fpartial-inlining -freorder-functions -O2 -s -z noexecstack -Xlinker -export-dynamic -rdynamic -Wl,-R,'/usr/lib' -Wl,--disable-new-dtags -Wl,-b -Wl,binary -Wl,./__constants.bin -Wl,-b -Wl,elf64-x86-64 -Wl,-defsym -Wl,constant_bin_data=_binary_____constants_bin_start @"./@link_input.txt" -L/usr/lib -ldl -lm "/usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a" -lz -lm -lutil -lpthread -lexpat</command>
      <stderr>
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA512Type_hexdigest':(.text+0x2ac): undefined reference to `python_hashlib_Hacl_Hash_SHA2_digest_512'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA512Type_digest':(.text+0x34c): undefined reference to `python_hashlib_Hacl_Hash_SHA2_digest_512'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA512_dealloc':(.text+0x3c2): undefined reference to `python_hashlib_Hacl_Hash_SHA2_free_512'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA256Type_hexdigest':(.text+0x45c): undefined reference to `python_hashlib_Hacl_Hash_SHA2_digest_256'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA256Type_digest':(.text+0x4fc): undefined reference to `python_hashlib_Hacl_Hash_SHA2_digest_256'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA256_dealloc':(.text+0x572): undefined reference to `python_hashlib_Hacl_Hash_SHA2_free_256'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA256Type_copy':(.text+0x6a4): undefined reference to `python_hashlib_Hacl_Hash_SHA2_copy_256'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA512Type_copy':(.text+0x785): undefined reference to `python_hashlib_Hacl_Hash_SHA2_copy_512'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA512Type_update':(.text+0x8af): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'/bin/ld: (.text+0x8c4): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'/bin/ld: (.text+0x924): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'/bin/ld: (.text+0x9ef): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA256Type_update':(.text+0xabf): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'/bin/ld: (.text+0xad4): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'/bin/ld: (.text+0xb34): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'/bin/ld: (.text+0xbff): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `_sha2_sha512':(.text+0xde8): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_512'/bin/ld: (.text+0xe21): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'/bin/ld: (.text+0xe86): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_512'/bin/ld: (.text+0xf47): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'/bin/ld: (.text+0xf66): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `_sha2_sha224':(.text+0x1146): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_224'/bin/ld: (.text+0x11af): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'/bin/ld: (.text+0x11ce): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'/bin/ld: (.text+0x125b): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_224'/bin/ld: (.text+0x12d2): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `_sha2_sha256':(.text+0x14a7): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_256'/bin/ld: (.text+0x150f): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'/bin/ld: (.text+0x152e): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'/bin/ld: (.text+0x15bc): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_256'/bin/ld: (.text+0x1632): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `_sha2_sha384':(.text+0x1818): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_384'/bin/ld: (.text+0x1851): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'/bin/ld: (.text+0x18b6): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_384'/bin/ld: (.text+0x1977): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'/bin/ld: (.text+0x1996): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'collect2: error: ld returned 1 exit status
</stderr>
    </scons_error_report>
  </scons_error_reports>
  <module name="__main__" kind="PythonMainModule" usage="root_module" reason="Root module" source_path="test.py">
    <optimization-time pass="1" time="0.00" />
    <optimization-time pass="2" time="0.00" />
    <module_usages>
      <module_usage name="site" finding="excluded" line="1" exclusion_reason="Not following into stdlib unless standalone or requested to follow into stdlib." />
    </module_usages>
  </module>
  <performance>
    <memory_usage name="after_launch" value="46903296" />
    <memory_usage name="before_c_code_generation" value="47099904" />
    <memory_usage name="before_running_scons" value="49852416" />
  </performance>
  <data_composer blob_size="1042" total="107">
    <module_data filename="__bytecode.const" input_size="0" blob_name=".bytecode" blob_size="3" />
    <module_data filename="__constants.const" input_size="2133" blob_name="" blob_size="895" />
    <module_data filename="module.__main__.const" input_size="205" blob_name="__main__" blob_size="104" />
  </data_composer>
  <command_line>
    <option value="test.py" />
  </command_line>
  <plugins>
    <plugin name="anti-bloat" user_enabled="no" />
    <plugin name="eventlet" user_enabled="no" />
    <plugin name="gi" user_enabled="no" />
    <plugin name="implicit-imports" user_enabled="no" />
    <plugin name="multiprocessing" user_enabled="no" />
    <plugin name="options-nanny" user_enabled="no" />
    <plugin name="pkg-resources" user_enabled="no" />
    <plugin name="transformers" user_enabled="no" />
  </plugins>
  <distributions />
  <python python_exe="${sys.prefix}/bin/python" python_flavor="Debian Python" python_version="3.12.4" os_name="Linux" os_release="Debian-sid" arch_name="x86_64">
    <search_path>
      <path value="${cwd}" />
      <path value="${sys.prefix}/bin" />
      <path value="${sys.real_prefix}/lib/python3.12" />
      <path value="${sys.real_prefix}/lib/python3.12/lib-dynload" />
      <path value="${sys.prefix}/lib/python3.12/site-packages" />
      <path value="~/.local/pipx/shared/lib/python3.12/site-packages" />
    </search_path>
  </python>
  <output run_filename="${cwd}/test.bin" />
</nuitka-compilation-report>
```

**Comment by kayhayen** [comment]
The Ubuntu packaging of Python3.12 was found to be garbage, the Debian packaging might be too. Nuitka contains an inline copy to work around omitted code from libpython3.12.a and we added an inline copy for that, that should be used on your side.

Can you show the output of `--show-scons` on hello world program?

**Comment by antsvil** [comment]
```
$ nuitka3 hello.py --show-scons
Nuitka-Options: Used command line options: hello.py --show-scons
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make
Nuitka-Options:WARNING: sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.3.10' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Scons command: /home/test/.local/share/pipx/venvs/nuitka/bin/python -W ignore
Nuitka-Scons: /home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/bin/scons.py
Nuitka-Scons: -f /home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/Backend.scons
Nuitka-Scons: --jobs 24 --warn=no-deprecated --no-site-dir --debug=stacktrace source_dir=. nuitka_python=false
Nuitka-Scons: debug_mode=false debugger_mode=false python_debug=false module_mode=false full_compat=false
Nuitka-Scons: experimental= trace_mode=false file_reference_mode=original module_count=1
Nuitka-Scons: result_exe=/home/test/hello.bin
Nuitka-Scons: static_libpython=/usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a
Nuitka-Scons: debian_python=true
Nuitka-Scons: nuitka_src=/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build
Nuitka-Scons: python_version=3.12 python_prefix=/usr no_deployment= show_scons=true target_arch=x86_64
scons: Reading SConscript files ...
Nuitka-Scons: CC '/bin/gcc' version check gives (13,)
Nuitka-Scons: Initial CC: 'gcc'
Nuitka-Scons: Initial CCVERSION: (13,)
Scons: Compiler used /bin/gcc 
Nuitka-Scons: Backend C compiler: gcc (gcc 13).
Nuitka-Scons: LTO mode auto was resolved to mode: 'yes' (known to be supported (Debian)).
Nuitka-Scons: Using C11 mode: True
Nuitka-Scons: Using resource mode: 'linker' (default for lto gcc with --lto bugs for incbin).
Nuitka-Scons: Inherited CFLAGS='-O3' variable.
Nuitka-Scons: Scons: Inherited CXXFLAGS='-O3' variable.
Nuitka-Scons: Told to run compilation on 24 CPUs.
Nuitka-Scons: Launching Scons target: ['/home/test/hello.bin']
scons: done reading SConscript files.
scons: Building targets ...
gcc -o __constants.o -c -flto=24 -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indentation -fcompare-debug-second -O2 -O3 -D__NUITKA_NO_ASSERT__ -DPy_NO_ENABLE_SHARED -D_NUITKA_STATIC_LIBPYTHON -D_NUITKA_USE_UNEXPOSED_API -D_NUITKA_CONSTANTS_FROM_LINKER -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -D_NUITKA_FILE_REFERENCE_ORIGINAL_MODE -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/zlib -I/usr/include/python3.12 -I. -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/include -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/static_src -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/libbacktrace __constants.c
gcc -o __helpers.o -c -flto=24 -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indentation -fcompare-debug-second -O2 -O3 -D__NUITKA_NO_ASSERT__ -DPy_NO_ENABLE_SHARED -D_NUITKA_STATIC_LIBPYTHON -D_NUITKA_USE_UNEXPOSED_API -D_NUITKA_CONSTANTS_FROM_LINKER -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -D_NUITKA_FILE_REFERENCE_ORIGINAL_MODE -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/zlib -I/usr/include/python3.12 -I. -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/include -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/static_src -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/libbacktrace __helpers.c
gcc -o __loader.o -c -flto=24 -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indentation -fcompare-debug-second -O2 -O3 -D__NUITKA_NO_ASSERT__ -DPy_NO_ENABLE_SHARED -D_NUITKA_STATIC_LIBPYTHON -D_NUITKA_USE_UNEXPOSED_API -D_NUITKA_CONSTANTS_FROM_LINKER -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -D_NUITKA_FILE_REFERENCE_ORIGINAL_MODE -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/zlib -I/usr/include/python3.12 -I. -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/include -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/static_src -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/libbacktrace __loader.c
gcc -o module.__main__.o -c -flto=24 -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indentation -fcompare-debug-second -O2 -O3 -D__NUITKA_NO_ASSERT__ -DPy_NO_ENABLE_SHARED -D_NUITKA_STATIC_LIBPYTHON -D_NUITKA_USE_UNEXPOSED_API -D_NUITKA_CONSTANTS_FROM_LINKER -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -D_NUITKA_FILE_REFERENCE_ORIGINAL_MODE -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/zlib -I/usr/include/python3.12 -I. -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/include -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/static_src -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/libbacktrace module.__main__.c
gcc -o static_src/MainProgram.o -c -flto=24 -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indentation -fcompare-debug-second -O2 -O3 -D__NUITKA_NO_ASSERT__ -DPy_NO_ENABLE_SHARED -D_NUITKA_STATIC_LIBPYTHON -D_NUITKA_USE_UNEXPOSED_API -D_NUITKA_CONSTANTS_FROM_LINKER -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -D_NUITKA_FILE_REFERENCE_ORIGINAL_MODE -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/zlib -I/usr/include/python3.12 -I. -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/include -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/static_src -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/libbacktrace static_src/MainProgram.c
gcc -o static_src/CompiledFunctionType.o -c -flto=24 -fuse-linker-plugin -fno-fat-lto-objects -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indentation -fcompare-debug-second -O2 -O3 -D__NUITKA_NO_ASSERT__ -DPy_NO_ENABLE_SHARED -D_NUITKA_STATIC_LIBPYTHON -D_NUITKA_USE_UNEXPOSED_API -D_NUITKA_CONSTANTS_FROM_LINKER -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -D_NUITKA_FILE_REFERENCE_ORIGINAL_MODE -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/zlib -I/usr/include/python3.12 -I. -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/include -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/static_src -I/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/libbacktrace static_src/CompiledFunctionType.c
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
gcc -o /home/test/hello.bin -flto=24 -fuse-linker-plugin -fpartial-inlining -freorder-functions -O2 -s -z noexecstack -Xlinker -export-dynamic -rdynamic -Wl,-R,'/usr/lib' -Wl,--disable-new-dtags -Wl,-b -Wl,binary -Wl,./__constants.bin -Wl,-b -Wl,elf64-x86-64 -Wl,-defsym -Wl,constant_bin_data=_binary_____constants_bin_start @"./@link_input.txt" -L/usr/lib -ldl -lm /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a -lz -lm -lutil -lpthread -lexpat
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA512Type_hexdigest':
(.text+0x2ac): undefined reference to `python_hashlib_Hacl_Hash_SHA2_digest_512'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA512Type_digest':
(.text+0x34c): undefined reference to `python_hashlib_Hacl_Hash_SHA2_digest_512'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA512_dealloc':
(.text+0x3c2): undefined reference to `python_hashlib_Hacl_Hash_SHA2_free_512'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA256Type_hexdigest':
(.text+0x45c): undefined reference to `python_hashlib_Hacl_Hash_SHA2_digest_256'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA256Type_digest':
(.text+0x4fc): undefined reference to `python_hashlib_Hacl_Hash_SHA2_digest_256'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA256_dealloc':
(.text+0x572): undefined reference to `python_hashlib_Hacl_Hash_SHA2_free_256'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA256Type_copy':
(.text+0x6a4): undefined reference to `python_hashlib_Hacl_Hash_SHA2_copy_256'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA512Type_copy':
(.text+0x785): undefined reference to `python_hashlib_Hacl_Hash_SHA2_copy_512'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA512Type_update':
(.text+0x8af): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'
/bin/ld: (.text+0x8c4): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'
/bin/ld: (.text+0x924): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'
/bin/ld: (.text+0x9ef): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `SHA256Type_update':
(.text+0xabf): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'
/bin/ld: (.text+0xad4): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'
/bin/ld: (.text+0xb34): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'
/bin/ld: (.text+0xbff): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `_sha2_sha512':
(.text+0xde8): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_512'
/bin/ld: (.text+0xe21): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'
/bin/ld: (.text+0xe86): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_512'
/bin/ld: (.text+0xf47): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'
/bin/ld: (.text+0xf66): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `_sha2_sha224':
(.text+0x1146): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_224'
/bin/ld: (.text+0x11af): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'
/bin/ld: (.text+0x11ce): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'
/bin/ld: (.text+0x125b): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_224'
/bin/ld: (.text+0x12d2): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `_sha2_sha256':
(.text+0x14a7): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_256'
/bin/ld: (.text+0x150f): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'
/bin/ld: (.text+0x152e): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'
/bin/ld: (.text+0x15bc): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_256'
/bin/ld: (.text+0x1632): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_256'
/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12-pic.a(sha2module.o): in function `_sha2_sha384':
(.text+0x1818): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_384'
/bin/ld: (.text+0x1851): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'
/bin/ld: (.text+0x18b6): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_384'
/bin/ld: (.text+0x1977): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'
/bin/ld: (.text+0x1996): undefined reference to `python_hashlib_Hacl_Hash_SHA2_update_512'
collect2: error: ld returned 1 exit status
scons: *** [/home/test/hello.bin] Error 1
scons: internal stack trace:
  File "/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Job.py", line 258, in run
    task.execute()
  File "/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Script/Main.py", line 206, in execute
    SCons.Taskmaster.OutOfDateTask.execute(self)
  File "/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Node/__init__.py", line 766, in build
    self.get_executor()(self, **kw)
  File "/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 397, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.local/share/pipx/venvs/nuitka/lib/python3.12/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 131, in execute_action_list
    raise status    # TODO pylint E0702: raising int not allowed
    ^^^^^^^^^^^^
scons: building terminated because of errors.
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.

```

**Comment by kayhayen** [comment]
The workaround originally devised for Ubuntu had not been applied unless standalone mode is used, with 2.4 which I just released it is applied to accelerated mode as well, covering of course Debian too.

**Comment by antsvil** [comment]
Tried with some projects that failed before, now it works fine. Thanks Kayhayen.
