### ISSUE TITLE
0.6.19rc2: Build "Interrupted while working on Node COMPILED_PYTHON_MODULE"

### ISSUE THREAD

**Issue by kamgha** [Nuitka/Nuitka#1302]
Nuitka 0.6.19rc2 (from source)
CPython 3.7.12 on Windows 7 SP1 64bit

Works with Nuitka 0.6.18.1, fails with Nuitka 0.6.19rc2.

`Running Nuitka with ..\path\to\python\python -m nuitka --plugin-enable=pylint-warnings --standalone --prefer-source-code --follow-stdlib --lto=yes --include-plugin-files=..\path\to\Pmw.py --python-flag=no_site,no_randomization,no_warnings,no_asserts,no_docstrings --disable-dll-dependency-cache --windows-disable-console ..\path\to\myproject.py`

Test case (needs `panda3d`, e, g. via `pip`):

```
from direct.showbase.ShowBase import ShowBase


class MyApp(ShowBase):

    def __init__(self):
        ShowBase.__init__(self)


app = MyApp()
app.run()
```

Nuitka prints out the following message and aborts the build process:

```
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.19rc2' on Python '3.7'
 commercial None.
Nuitka-Plugins:WARNING: Use '--enable-plugin=pmw-freezer' for: Proper freezing o
f Pmw package.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter'
 added '_tkinter'.
                                                                               P
roblem with statement at D:\ntest\panda3d-editor-win64\direct\showbase\ShowBase.
py:1834:
->             physics = importlib.import_module('panda3d.physics')

Problem with statement at D:\ntest\panda3d-editor-win64\direct\showbase\ShowBase
.py:1833:
->         if not self.physicsMgrAngular:

Problem with statement at D:\ntest\panda3d-editor-win64\direct\showbase\ShowBase
.py:1827:
->     def addAngularIntegrator(self):

Problem with statement at D:\ntest\panda3d-editor-win64\direct\showbase\ShowBase
.py:1827:
->     def addAngularIntegrator(self):

Problem with statement at D:\ntest\panda3d-editor-win64\direct\showbase\ShowBase
.py:85:
-> class ShowBase(DirectObject.DirectObject):

Problem with statement at D:\ntest\panda3d-editor-win64\direct\showbase\ShowBase
.py:85:
-> class ShowBase(DirectObject.DirectObject):

Problem with statement at D:\ntest\panda3d-editor-win64\direct\showbase\ShowBase
.py:85:
-> class ShowBase(DirectObject.DirectObject):

Problem with statement at D:\ntest\panda3d-editor-win64\direct\showbase\ShowBase
.py:85:
-> class ShowBase(DirectObject.DirectObject):

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {
'filename': 'D:\\ntest\\panda3d-editor-win64\\direct\\showbase\\ShowBase.py', 'm
odule_name': <ModuleName direct.showbase.ShowBase>, 'code_flags': ''}>'.
PASS 1:  99%|████████████████████████████████████████████████████████?| 176/177T
raceback (most recent call last):
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\__main__.py", line 142, in <module>
    main()
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\__main__.py", line 128, in main
    MainControl.main()
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\MainControl.py", line 906, in main
    main_module = _createNodeTree(filename=filename)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\MainControl.py", line 193, in _createNo
deTree
    optimizeModules(main_module.getOutputFilename())
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\Optimization.py", line 35
0, in optimizeModules
    finished = makeOptimizationPass()
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\Optimization.py", line 31
2, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\Optimization.py", line 20
7, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\Optimization.py", line 10
3, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\ModuleNodes.py", line 529, in com
puteModule
    trace_collection=self.trace_collection
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\StatementNodes.py", line 163, in
computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\FrameNodes.py", line 182, in comp
uteStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 615, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\TryNodes.py", line 105, in comput
eStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\StatementNodes.py", line 165, in
computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 615, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\AssignNodes.py", line 275, in com
puteStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 596, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\OutlineNodes.py", line 240, in co
mputeExpressionRaw
    result = body.computeStatementsSequence(trace_collection=trace_collection)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\StatementNodes.py", line 165, in
computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 615, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\TryNodes.py", line 105, in comput
eStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\StatementNodes.py", line 165, in
computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 615, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\TryNodes.py", line 105, in comput
eStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\StatementNodes.py", line 163, in
computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\FrameNodes.py", line 182, in comp
uteStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 615, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\LocalsDictNodes.py", line 400, in
 computeStatement
    trace_collection=trace_collection
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\NodeBases.py", line 897, in compu
teStatementSubExpressions
    expression = trace_collection.onExpression(expression=expression)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 596, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\ExpressionBases.py", line 1164, i
n computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 596, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\FunctionNodes.py", line 1090, in
computeExpressionRaw
    trace_collection.onUsedFunction(self.getFunctionBody())
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 482, in onUsedFunction
    function_body.computeFunctionRaw(self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\FunctionNodes.py", line 495, in c
omputeFunctionRaw
    self.computeFunction(trace_collection)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\FunctionNodes.py", line 511, in c
omputeFunction
    trace_collection=trace_collection
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\StatementNodes.py", line 165, in
computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 615, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\TryNodes.py", line 105, in comput
eStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\StatementNodes.py", line 163, in
computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\FrameNodes.py", line 182, in comp
uteStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 615, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\ConditionalNodes.py", line 568, i
n computeStatement
    branch_yes_collection.computeBranch(branch=yes_branch)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 914, in computeBranch
    result = branch.computeStatementsSequence(trace_collection=self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\StatementNodes.py", line 165, in
computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 615, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\AssignNodes.py", line 275, in com
puteStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\optimizations\TraceCollections.py", lin
e 596, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\ImportNodes.py", line 284, in com
puteExpressionRaw
    self._attemptRecursion(trace_collection)
  File "D:\ntest\Nuitka-0.6.19rc2\nuitka\nodes\ImportNodes.py", line 267, in _at
temptRecursion
    package_module = self._consider(
AttributeError: 'ExpressionImportModuleFixed' object has no attribute '_consider
'
```

Note: As opposed to issue #1271 which contains the same example reproducer, this version of Nuitka prints out `Problem with statement at` messages. I'm not sure what it means here.

You can find `ShowBase.py` here: https://github.com/panda3d/panda3d/blob/master/direct/src/showbase/ShowBase.py

**Comment by kayhayen** [comment]
This is due to enhanced static optimization, revealing bugs in previous `importlib.import_module` optimization, I rebased master and develop branch ahead of a hotfix to make it never have had the issue, as it's too bad for git bisection. There a few things that are like that, where enhanced optimization makes old bugs visible. So I am going to do this even more now.
